import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from 'react';
import { cn } from '@/lib/utils';
export function VariantsSidebar({ component, selectedVariant, onVariantSelect, props, onPropsChange, isOpen, }) {
    if (!isOpen || !component)
        return null;
    const hasVariants = component.variants && component.variants.length > 0;
    const hasProps = component.props.length > 0;
    const handlePropChange = (name, value) => {
        onPropsChange({ ...props, [name]: value });
    };
    return (_jsxs("div", { className: "w-72 shrink-0 border-l border-border bg-background overflow-y-auto", children: [hasVariants && (_jsxs("div", { className: "p-4 border-b border-border", children: [_jsx("h2", { className: "text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3", children: "Variants" }), _jsx("div", { className: "space-y-1", children: component.variants.map(variant => (_jsxs("button", { onClick: () => onVariantSelect(variant), className: cn('w-full text-left px-3 py-2 rounded-md text-sm transition-colors', selectedVariant === variant.name
                                ? 'bg-foreground/10 text-foreground font-medium'
                                : 'text-muted-foreground hover:bg-foreground/5 hover:text-foreground'), children: [_jsx("div", { children: variant.name }), variant.description && (_jsx("div", { className: "text-xs mt-0.5 line-clamp-2 text-muted-foreground", children: variant.description }))] }, variant.name))) })] })), hasProps && (_jsxs("div", { className: "p-4", children: [_jsx("h2", { className: "text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3", children: "Props" }), _jsx("div", { className: "space-y-3", children: component.props.map(propDef => (_jsx(PropControl, { definition: propDef, value: props[propDef.name], onChange: value => handlePropChange(propDef.name, value) }, propDef.name))) })] })), !hasVariants && !hasProps && (_jsx("div", { className: "p-4", children: _jsx("p", { className: "text-sm text-muted-foreground italic", children: "No variants or props defined." }) }))] }));
}
function PropControl({ definition, value, onChange }) {
    const { name, description, control } = definition;
    return (_jsxs("div", { className: "space-y-1", children: [_jsxs("div", { className: "flex flex-col gap-0.5", children: [_jsx("label", { className: "text-sm font-medium text-foreground", children: name }), description && (_jsx("span", { className: "text-xs text-muted-foreground", children: description }))] }), control.type === 'boolean' && (_jsx("button", { onClick: () => onChange(!value), className: cn('px-3 py-1.5 rounded-md text-xs font-mono transition-colors', value
                    ? 'bg-green-500/20 text-green-600 dark:text-green-400'
                    : 'bg-foreground/5 text-muted-foreground'), children: String(value) })), control.type === 'string' && (_jsx("input", { type: "text", value: String(value ?? ''), onChange: e => onChange(e.target.value), placeholder: control.placeholder, className: "w-full px-3 py-1.5 rounded-md bg-foreground/5 border border-border text-sm focus:outline-none focus:ring-1 focus:ring-ring" })), control.type === 'textarea' && (_jsx("textarea", { value: String(value ?? ''), onChange: e => onChange(e.target.value), placeholder: control.placeholder, rows: control.rows ?? 3, className: "w-full px-3 py-1.5 rounded-md bg-foreground/5 border border-border text-sm font-mono resize-y focus:outline-none focus:ring-1 focus:ring-ring" })), control.type === 'number' && (_jsx("input", { type: "number", value: Number(value ?? 0), onChange: e => onChange(Number(e.target.value)), min: control.min, max: control.max, step: control.step, className: "w-24 px-3 py-1.5 rounded-md bg-foreground/5 border border-border text-sm focus:outline-none focus:ring-1 focus:ring-ring" })), control.type === 'select' && (_jsx("select", { value: String(value ?? ''), onChange: e => onChange(e.target.value), className: "w-full px-3 py-1.5 rounded-md bg-foreground/5 border border-border text-sm focus:outline-none focus:ring-1 focus:ring-ring", children: control.options.map(opt => (_jsx("option", { value: opt.value, children: opt.label }, opt.value))) }))] }));
}
//# sourceMappingURL=VariantsSidebar.js.map