/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Hardcoded schemas for the cua-driver computer-use tools.
 *
 * Pinned to: cua-driver-rs v0.5.2 (see CUA_DRIVER_VERSION in constants.ts).
 *
 * Generated from the live `cua-driver mcp` `tools/list` output — the FULL
 * tool surface cua-driver advertises (no curation). Exposing the complete set
 * (including page/CDP, cursor, session, recording, config, kill_app, …) so the
 * model has every capability cua-driver actually provides.
 *
 * Regenerated by scripts/sync-computer-use-schemas.ts — do not hand-edit.
 */

export interface ComputerUseToolSchema {
  description: string;
  parameterSchema: Record<string, unknown>;
}

export const COMPUTER_USE_TOOL_NAMES = [
  'bring_to_front',
  'check_for_update',
  'check_permissions',
  'click',
  'double_click',
  'drag',
  'end_session',
  'get_accessibility_tree',
  'get_agent_cursor_state',
  'get_config',
  'get_cursor_position',
  'get_recording_state',
  'get_screen_size',
  'get_window_state',
  'hotkey',
  'kill_app',
  'launch_app',
  'list_apps',
  'list_windows',
  'move_cursor',
  'page',
  'press_key',
  'replay_trajectory',
  'right_click',
  'scroll',
  'set_agent_cursor_enabled',
  'set_agent_cursor_motion',
  'set_agent_cursor_style',
  'set_config',
  'set_value',
  'start_recording',
  'start_session',
  'stop_recording',
  'type_text',
  'zoom',
] as const;

export type ComputerUseToolName = (typeof COMPUTER_USE_TOOL_NAMES)[number];

export const COMPUTER_USE_SCHEMAS: Record<
  ComputerUseToolName,
  ComputerUseToolSchema
> = {
  bring_to_front: {
    description:
      'Activate a window so subsequent input tools with `dispatch:"foreground"` land on it without a per-call SetForegroundWindow flash. **Windows-only:** on macOS this tool returns an error pointing to the platform-native `NSRunningApplication.activate` (which the macOS input tools don\'t need because CGEvent.postToPid reaches backgrounded windows). On Linux this tool also stubs out; use `wmctrl -a` or `xdotool windowactivate` if you need explicit activation.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        pid: {
          type: 'integer',
        },
        window_id: {
          type: 'integer',
        },
      },
      required: ['pid'],
      type: 'object',
    },
  },
  check_for_update: {
    description:
      'Check whether a newer cua-driver-rs release is available on GitHub. Returns the current and latest versions, an `update_available` boolean, the install one-liner, and the release notes URL. Read-only — never installs. Mirror of `cua-driver check-update --json`.',
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  check_permissions: {
    description:
      "Report TCC permission status for Accessibility and Screen Recording. By default also raises the system permission dialogs for any missing grants — Apple's request APIs are no-ops when the grant is already active, so this is safe to call repeatedly. Pass {\"prompt\": false} for a purely read-only status check.\n\nReturns: `accessibility` + `screen_recording` (booleans from the TCC preflight APIs), `screen_recording_capturable` (a live ScreenCaptureKit probe — if it disagrees with `screen_recording`, the preflight grant belongs to a different process), and `source` (which TCC identity the booleans reflect: the CuaDriver daemon vs the launching terminal/IDE). macOS attributes grants to the responsible process, so a standalone call from a terminal reports the terminal's grants, not the driver's.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        prompt: {
          description:
            'Raise the system permission prompts for missing grants. Default true.',
          type: 'boolean',
        },
      },
      type: 'object',
    },
  },
  click: {
    description:
      "Left-click against a target pid. **Prefer `element_index` over pixel coordinates** — element_index works on backgrounded / minimized / hidden / off-Space windows, surfaces a stable handle that survives rebuilds, and tells you what you're clicking via the cached element's role + label. Reach for `x, y` only when the target is a canvas / video / WebGL / custom-drawn surface that doesn't appear in the AX tree.\n\nTwo addressing modes:\n\n- element_index + window_id (from last get_window_state): AX action path. Works on backgrounded/hidden windows. No cursor move, no focus steal. element_index cache is scoped per (pid, window_id) and is replaced by the next snapshot of the same window — re-snapshot every turn before clicking.\n\n- x, y (window-local screenshot pixels, top-left origin of the PNG returned by get_window_state): CGEvent path. Synthesizes mouse events and posts to pid. Use modifier for cmd/shift/option/ctrl. Needs a visible on-screen window to anchor the conversion.\n\naction: press (default), show_menu, pick, confirm, cancel, open.\nfrom_zoom: set true after a zoom call to auto-translate zoom-image pixel coordinates to full-window space.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        action: {
          description:
            'AX action: press, show_menu, pick, confirm, cancel, open.',
          type: 'string',
        },
        count: {
          description: 'Click count (pixel path only). Default 1.',
          type: 'integer',
        },
        debug_image_out: {
          description:
            'Optional file path. When set on a pixel-addressed click, captures a fresh screenshot, draws a red crosshair at (x, y), and writes the PNG. Use to verify coordinate spaces. Requires window_id; incompatible with from_zoom.',
          type: 'string',
        },
        element_index: {
          description: 'Element index from last get_window_state.',
          type: 'integer',
        },
        from_zoom: {
          description:
            'When true, x and y are in the last zoom image for this pid; driver translates back to full-window coordinates.',
          type: 'boolean',
        },
        modifier: {
          description: 'Modifier keys: cmd, shift, option/alt, ctrl.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          description: 'Target window ID. Required for element_index.',
          type: 'integer',
        },
        x: {
          description: 'Window-local screenshot X coordinate.',
          type: 'number',
        },
        y: {
          description: 'Window-local screenshot Y coordinate.',
          type: 'number',
        },
      },
      required: ['pid'],
      type: 'object',
    },
  },
  double_click: {
    description:
      "Double-click at (x, y) or on an AX element identified by element_index + window_id.\n\nAX path (element_index provided): performs `AXOpen` when the element advertises it (Finder items, openable list rows/cells); otherwise resolves the element's on-screen center and falls back to a pixel double-click there.\n\nPixel path (x, y provided): two down/up pairs ~80 ms apart at the given coordinates.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        element_index: {
          description:
            'Element index from last get_window_state. Uses AX path.',
          type: 'integer',
        },
        pid: {
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          description: 'CGWindowID. Required when element_index is used.',
          type: 'integer',
        },
        x: {
          description: 'Screen X coordinate (pixel path).',
          type: 'number',
        },
        y: {
          description: 'Screen Y coordinate (pixel path).',
          type: 'number',
        },
      },
      required: ['pid'],
      type: 'object',
    },
  },
  drag: {
    description:
      "Press-drag-release gesture from (from_x, from_y) to (to_x, to_y) in window-local screenshot pixels — the same space get_window_state returns. Top-left origin of the target's window.\n\nUse for: marquee/lasso selection, drag-and-drop, resizing via a handle, scrubbing a slider, repositioning a panel.\n\n`duration_ms` (default 500) is the wall-clock budget for the path between mouse-down and mouse-up; `steps` (default 20) is the number of intermediate mouseDragged events linearly interpolated along the path. Increase both for slower, more human drags; decrease for snap gestures.\n\n`modifier` keys (cmd/shift/option/ctrl) are held across the entire gesture.\n\nWhen `from_zoom` is true, coordinates are in the last zoom image for this pid; the driver maps them back to window coordinates before dispatching.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        button: {
          description: 'Mouse button used for the drag. Default: left.',
          enum: ['left', 'right', 'middle'],
          type: 'string',
        },
        duration_ms: {
          description:
            'Wall-clock duration of the drag path between mouseDown and mouseUp. Default: 500.',
          maximum: 10000,
          minimum: 0,
          type: 'integer',
        },
        from_x: {
          description:
            'Drag-start X in window-local screenshot pixels. Top-left origin.',
          type: 'number',
        },
        from_y: {
          description:
            'Drag-start Y in window-local screenshot pixels. Top-left origin.',
          type: 'number',
        },
        from_zoom: {
          description:
            'When true, coordinates are in the last zoom image for this pid; driver maps back to window coordinates.',
          type: 'boolean',
        },
        modifier: {
          description:
            'Modifier keys held across the entire gesture: cmd/shift/option/ctrl.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        steps: {
          description:
            'Number of intermediate mouseDragged events linearly interpolated along the path. Default: 20.',
          maximum: 200,
          minimum: 1,
          type: 'integer',
        },
        to_x: {
          description: 'Drag-end X in window-local screenshot pixels.',
          type: 'number',
        },
        to_y: {
          description: 'Drag-end Y in window-local screenshot pixels.',
          type: 'number',
        },
        window_id: {
          description:
            'CGWindowID for the window the pixel coordinates were measured against. Optional — when omitted the driver picks the frontmost window of pid.',
          type: 'integer',
        },
      },
      required: ['pid', 'from_x', 'from_y', 'to_x', 'to_y'],
      type: 'object',
    },
  },
  end_session: {
    description:
      "End a session declared with `start_session`: removes its agent cursor, stops any recording it owns, and clears its per-session config. Call this when a run finishes so its cursor doesn't linger (otherwise the idle-TTL reclaims it after a period of inactivity). Idempotent.",
    parameterSchema: {
      additionalProperties: true,
      properties: {
        session: {
          description: 'The session id to end.',
          type: 'string',
        },
      },
      required: ['session'],
      type: 'object',
    },
  },
  get_accessibility_tree: {
    description:
      "Return a lightweight snapshot of the desktop: running regular apps and on-screen visible windows with their bounds, z-order, and owner pid.\n\nFor the full AX subtree of a single window (with interactive element indices you can click by), use `get_window_state` instead — that's the heavy per-window tool. This one is a fast discovery read that needs no TCC grants.",
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  get_agent_cursor_state: {
    description:
      "Return the current state of THIS session's agent cursor: position, config (color, icon, label, size, opacity), enabled flag. Pass cursor_id to inspect a specific instance.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        cursor_id: {
          description: "Cursor instance. Default: this session's cursor.",
          type: 'string',
        },
      },
      type: 'object',
    },
  },
  get_config: {
    description: 'Return the current cua-driver-rs configuration.',
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  get_cursor_position: {
    description:
      'Return the current mouse cursor position in screen points (origin top-left).',
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  get_recording_state: {
    description:
      'Report the current trajectory recorder state: whether recording is enabled, the output directory (when enabled), and the 1-based counter for the next turn folder that will be written. Counter increments on every recorded action tool call and resets to 1 each time recording is (re-)enabled.\n\nPure read-only.',
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  get_screen_size: {
    description:
      'Return the logical size of the main display in points plus its backing scale factor. Agents click in points; Retina displays have scale_factor 2.0. Requires no TCC permissions.',
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  get_window_state: {
    description:
      "Walk a running app's AX tree and return a Markdown rendering of its UI, tagging every actionable element with [element_index N]. Pass those indices to click, type_text, press_key, etc.\n\nINVARIANT: call get_window_state once per turn per (pid, window_id) before any element-indexed action. The index map is replaced by the next snapshot.\n\nAlso captures a PNG screenshot of the specified window.\n\nOptional `query` filters the tree_markdown to matching lines plus their ancestor chain (case-insensitive substring). The element_index values are unchanged — filtering only trims the rendered Markdown.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        capture_mode: {
          description:
            'som=AX+screenshot (default), vision=screenshot only (no AX walk), ax=AX only (no screenshot).',
          enum: ['som', 'vision', 'ax'],
          type: 'string',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        query: {
          description: 'Case-insensitive filter for tree_markdown.',
          type: 'string',
        },
        screenshot_out_file: {
          description:
            'When set, write the PNG to this file path (~ expanded) instead of embedding base64 in the response. The structured output will contain screenshot_file_path instead.',
          type: 'string',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          description: 'Target window ID from list_windows.',
          type: 'integer',
        },
      },
      required: ['pid', 'window_id'],
      type: 'object',
    },
  },
  hotkey: {
    description:
      'Press a combination of keys simultaneously — e.g. `["cmd", "c"]` for Copy, `["cmd", "shift", "4"]` for screenshot selection. The combo is posted directly to the target pid\'s event queue; the target does NOT need to be frontmost.\n\nTwo delivery paths:\n• Default (no window_id): auth-message envelope — Chromium/Electron apps accept the keystrokes as trusted live input on macOS 14+.\n• With window_id: NSMenu path — briefly activates the target WindowServer-frontmost via SLPSSetFrontProcessWithOptions (kCPSNoWindows, < 1 ms), posts WITHOUT the auth envelope so IOHIDPostEvent fires and NSApplication.sendEvent: dispatches NSMenu key equivalents (e.g. Cmd+Z undo, Cmd+W close). Restores prior frontmost immediately. Use this path when you need native menu-bar actions on non-Chromium apps.\n\nRecognized modifiers: cmd/command, shift, option/alt, ctrl/control, fn. Non-modifier keys use the same vocabulary as `press_key` (return, tab, escape, up/down/left/right, space, delete, home, end, pageup, pagedown, f1-f12, letters, digits). Order: modifiers first, one non-modifier last.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        keys: {
          description:
            'Modifier(s) and one non-modifier key, e.g. ["cmd", "c"].',
          items: {
            type: 'string',
          },
          minItems: 2,
          type: 'array',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          description:
            'When set, uses NSMenu path: briefly activates the window for menu key dispatch, then restores prior frontmost.',
          type: 'integer',
        },
      },
      required: ['pid', 'keys'],
      type: 'object',
    },
  },
  kill_app: {
    description:
      'Force-terminate a process by pid (kill -9 equivalent on macOS / Linux; taskkill /F equivalent on Windows). Use as escalation when the cooperative close path (hotkey cmd+q on macOS, click-the-X on Windows) failed to make the process exit. Unsaved state is lost — prefer the cooperative path first.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        pid: {
          description: 'PID of the process to terminate.',
          type: 'integer',
        },
      },
      required: ['pid'],
      type: 'object',
    },
  },
  launch_app: {
    description:
      'Launch a macOS app in the background — the target does NOT come to the foreground.\n\nProvide either `bundle_id` (preferred — unambiguous, e.g. `com.apple.calculator`) or `name` (e.g. "Calculator"). If both are given, bundle_id wins.\n\nOptional `urls` are handed to the app as open targets — for Finder, pass a folder path to open a backgrounded Finder window there.\n\nOptional `electron_debugging_port`: opens a Chrome DevTools Protocol (CDP) server on the specified port (appends --remote-debugging-port=N to the app\'s argv). Use this to automate Electron/VS Code/Cursor via CDP.\n\nOptional `webkit_inspector_port`: opens a WebKit inspector server on the specified port (sets WEBKIT_INSPECTOR_SERVER=127.0.0.1:N + TAURI_WEBVIEW_AUTOMATION=1). Use this for Tauri/WebKit-based apps.\n\nOptional `creates_new_application_instance`: when true, forces a new app instance even if one is already running (passes -n to open). Reach for this when another agent or session may drive the SAME app concurrently — it returns a fresh pid + window so each session acts on its own isolated window instead of clobbering one shared instance. Without it, single-instance apps (Calculator, many utilities) hand every caller the same window, so two sessions fight over it.\n\nOptional `additional_arguments`: extra argv strings appended after --args.\n\nReturns the launched app\'s pid, bundle_id, name, and a `windows` array (same shape as `list_windows`) so callers can skip an extra round-trip before `get_window_state(pid, window_id)`. When the focus-steal belt-and-braces demotion check ran (target pid ≠ prior frontmost), the response also includes `self_activation_suppressed: bool` — true if focus stayed with the prior frontmost, false if the launched app held focus despite the re-demote attempt.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        additional_arguments: {
          description: 'Extra arguments appended after --args when launching.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        bundle_id: {
          description:
            'App bundle identifier, e.g. com.apple.calculator. Preferred over name.',
          type: 'string',
        },
        creates_new_application_instance: {
          description:
            'When true, force a new app instance even if already running (open -n). Use for concurrent multi-agent/multi-session work so each session gets an isolated instance + window instead of sharing one — on single-instance apps (e.g. Calculator) every caller otherwise gets the same window and the sessions clobber each other.',
          type: 'boolean',
        },
        electron_debugging_port: {
          description:
            'Open a Chrome DevTools Protocol server on this port (appends --remote-debugging-port=N).',
          type: 'integer',
        },
        name: {
          description: 'App display name. Used only when bundle_id is absent.',
          type: 'string',
        },
        urls: {
          description:
            'Optional file paths or URLs to open with the app (e.g. a folder path for Finder).',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        webkit_inspector_port: {
          description:
            'Open a WebKit inspector server on this port (sets WEBKIT_INSPECTOR_SERVER env var).',
          type: 'integer',
        },
      },
      type: 'object',
    },
  },
  list_apps: {
    description:
      'List macOS apps — both currently running and installed-but-not-running — with per-app state flags:\n\n- running: is a process for this app live? (pid is 0 when false)\n- active: is it the system-frontmost app? (implies running)\n- launch_path: filesystem path to the `.app` bundle, when known. Pass this to `launch_app` to start the app cold.\n- kind: `"desktop"` for `.app` bundles on macOS.\n- last_used: RFC3339 timestamp from the bundle\'s filesystem mtime, when readable; otherwise null.\n\nOnly apps with NSApplicationActivationPolicyRegular are included — background helpers and system UI agents are filtered out. Installed apps come from scanning /Applications, /Applications/Utilities, ~/Applications, /System/Applications, and /System/Applications/Utilities.\n\nUse this for "is X installed?" as well as "is X running?". For per-window state — on-screen, on-current-Space, minimized, window titles — call list_windows instead. For just opening an app — running or not — call launch_app({bundle_id: ...}) directly; list_apps is not a prerequisite.',
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  list_windows: {
    description:
      'List all layer-0 top-level windows currently known to WindowServer. Includes off-screen windows (minimized, on another Space, hidden-launched). Use this to find a window_id before calling get_window_state.\n\nPer-record fields: window_id, pid, app_name, title, bounds (x/y/width/height, top-left origin), z_index (higher = frontmost), is_on_screen, on_current_space.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        on_screen_only: {
          description:
            'When true, drop windows not on the current Space. Default false.',
          type: 'boolean',
        },
        pid: {
          description:
            "Optional pid filter. When set, only this pid's windows are returned.",
          type: 'integer',
        },
      },
      type: 'object',
    },
  },
  move_cursor: {
    description:
      "Move the agent cursor overlay to (x, y). Does NOT move the real mouse cursor — the user's cursor stays where it is. Useful for showing the agent's attention without interrupting the user.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        cursor_id: {
          description: "Cursor instance to move. Default: 'default'.",
          type: 'string',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        x: {
          type: 'number',
        },
        y: {
          type: 'number',
        },
      },
      required: ['x', 'y'],
      type: 'object',
    },
  },
  page: {
    description:
      "Interact with the browser page loaded in a running app. Supports Chrome, Brave, Edge, Safari (via AppleScript on macOS), Electron apps (via CDP), Chromium/Firefox on Windows (via UIA for read; CDP for execute_javascript when --remote-debugging-port is set), and WKWebView/Tauri/AT-SPI fallbacks.\n\nActions:\n- execute_javascript: Run JS and return the result.\n- get_text: Extract visible text from the page.\n- query_dom: Find elements matching a CSS selector.\n- click_element: Click a CSS-selected element AND animate the agent cursor to its on-screen center first (so the user sees what the agent is doing). Prefer over `execute_javascript('el.click()')` whenever you want visible cursor feedback.\n- enable_javascript_apple_events: macOS-only — patch the browser's Preferences to allow JS from Apple Events (Chrome/Brave/Edge, requires user confirmation and a browser restart).",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        action: {
          description: 'Action to perform.',
          enum: [
            'execute_javascript',
            'get_text',
            'query_dom',
            'click_element',
            'enable_javascript_apple_events',
          ],
          type: 'string',
        },
        attributes: {
          description: 'Element attributes to include in query_dom results.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        bundle_id: {
          description:
            'Bundle ID of the browser. Required for enable_javascript_apple_events (macOS only).',
          type: 'string',
        },
        css_selector: {
          description:
            "CSS selector for query_dom (e.g. 'a', 'button', 'input', 'h1'-'h6', 'p', 'img', 'select', '*').",
          type: 'string',
        },
        javascript: {
          description:
            'JavaScript to execute. Required for execute_javascript.',
          type: 'string',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        selector: {
          description:
            "CSS selector for click_element (e.g. 'button.submit', '#login a').",
          type: 'string',
        },
        user_has_confirmed_enabling: {
          description:
            'Must be true to proceed with enable_javascript_apple_events. This will quit and relaunch the browser.',
          type: 'boolean',
        },
        window_id: {
          description: 'Target window ID from list_windows.',
          type: 'integer',
        },
      },
      required: ['action'],
      type: 'object',
    },
  },
  press_key: {
    description:
      'Press and release a single key, delivered to the target pid via CGEventPostToPid. No focus steal.\n\nTwo delivery paths:\n• window_id + element_index: focuses the AX element first, then posts via the auth-message path (Chromium-safe).\n• window_id only (no element_index): NSMenu path — briefly activates the window WindowServer-frontmost via SLPSSetFrontProcessWithOptions (kCPSNoWindows, < 1 ms), posts WITHOUT the auth envelope so IOHIDPostEvent fires and NSApplication.sendEvent: dispatches NSMenu key equivalents. Restores prior frontmost immediately.\n• No window_id: standard auth-message path.\n\nKey names: return, tab, escape, up/down/left/right, space, delete, home, end, pageup, pagedown, f1-f12, plus any letter or digit.\nModifiers array: cmd, shift, option/alt, ctrl, fn.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        element_index: {
          type: 'integer',
        },
        key: {
          description: 'Key name: return, tab, escape, up, down, etc.',
          type: 'string',
        },
        modifiers: {
          description: 'Modifier keys: cmd, shift, option/alt, ctrl, fn.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        pid: {
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          type: 'integer',
        },
      },
      required: ['pid', 'key'],
      type: 'object',
    },
  },
  replay_trajectory: {
    description:
      "Replay a recorded trajectory by re-invoking every turn's tool call in lexical order. `dir` must point at a directory previously written by `start_recording`. Each `turn-NNNNN/` is parsed for `action.json`, and the recorded tool is called with its recorded `arguments` via the same dispatch path an MCP / CLI call uses.\n\nCaveats:\n- Element-indexed actions (`click({pid, element_index})` etc.) will fail because element indices are per-snapshot and don't survive across sessions. Pixel clicks (`click({pid, x, y})`) and all keyboard tools replay cleanly. Failures are reported but don't stop replay unless `stop_on_error` is true.\n- `get_window_state` and other read-only tools are NOT currently recorded, so replays do not re-populate the per-(pid, window_id) element cache.\n- If recording is ENABLED while replay runs, the replay itself is recorded into the currently configured output directory.  That's deliberate: recording a replay against a new build and diffing the two trajectories is the regression-test workflow.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        delay_ms: {
          description:
            'Milliseconds to sleep between turns, for human-observable pacing. Default 500.',
          maximum: 10000,
          minimum: 0,
          type: 'integer',
        },
        dir: {
          description:
            'Trajectory directory previously written by `set_recording`. Absolute or ~-rooted.',
          type: 'string',
        },
        stop_on_error: {
          description:
            'Stop replay on the first tool-call error. Default true — set false to best-effort through the full trajectory.',
          type: 'boolean',
        },
      },
      required: ['dir'],
      type: 'object',
    },
  },
  right_click: {
    description:
      "Right-click against a target pid. Two addressing modes:\n\n- `element_index` + `window_id` (from the last `get_window_state` snapshot) — performs `AXShowMenu` on the cached element. Pure AX RPC, works on backgrounded / hidden windows, no cursor move or focus steal. Requires a prior `get_window_state(pid, window_id)` in this turn.\n\n- `x`, `y` — synthesizes `rightMouseDown` / `rightMouseUp` CGEvent pair posted to the pid. Driver converts image-pixel → screen-point internally. `modifier` forces the CGEvent path (AX actions don't propagate modifier keys).\n\nExactly one of `element_index` or (`x` AND `y`) must be provided. `pid` always required. `window_id` required when `element_index` is used.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        element_index: {
          description:
            'Element index from last get_window_state. Routes through AXShowMenu. Requires window_id.',
          type: 'integer',
        },
        modifier: {
          description:
            'Modifier keys held during the right-click: cmd/shift/option/ctrl. Pixel path only.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          description: 'CGWindowID. Required when element_index is used.',
          type: 'integer',
        },
        x: {
          description:
            'X in window-local screenshot pixels. Must be provided together with y.',
          type: 'number',
        },
        y: {
          description:
            'Y in window-local screenshot pixels. Must be provided together with x.',
          type: 'number',
        },
      },
      required: ['pid'],
      type: 'object',
    },
  },
  scroll: {
    description:
      "Scroll the target pid's focused region by synthesized keystrokes.\n\nMapping: by='page' → PageDown/PageUp × amount; by='line' → DownArrow/UpArrow × amount. Horizontal variants use Left/Right arrow keys.\n\nOptional element_index + window_id pre-focuses the element before scrolling.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        amount: {
          description: 'Number of keystroke repetitions. Default: 3.',
          maximum: 50,
          minimum: 1,
          type: 'integer',
        },
        by: {
          description: 'Scroll granularity. Default: line.',
          enum: ['line', 'page'],
          type: 'string',
        },
        direction: {
          description: 'Scroll direction.',
          enum: ['up', 'down', 'left', 'right'],
          type: 'string',
        },
        element_index: {
          type: 'integer',
        },
        pid: {
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        window_id: {
          type: 'integer',
        },
      },
      required: ['pid', 'direction'],
      type: 'object',
    },
  },
  set_agent_cursor_enabled: {
    description:
      "Show or hide the agent cursor for a session. A cursor exists only for a DECLARED session: pass `session` (the same id you start_session / drive actions with) and the cursor appears on that session's first action — its color is derived from the id. Without a `session`, actions run cursor-less. Use enabled=false to hide a session's cursor, enabled=true to re-show it. (`cursor_id` is a legacy alias for `session`.)",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        cursor_id: {
          description: "Cursor instance. Default: 'default'.",
          type: 'string',
        },
        enabled: {
          description: 'true = show, false = hide.',
          type: 'boolean',
        },
      },
      required: ['enabled'],
      type: 'object',
    },
  },
  set_agent_cursor_motion: {
    description:
      "Configure the visual appearance and motion curve of an agent cursor instance.\n\nAppearance (multi-cursor customization):\n- cursor_id: instance name (default='default')\n- cursor_icon: built-in ('arrow','crosshair','hand','dot') or PNG/SVG file path\n- cursor_color: hex color e.g. '#00FFFF' or CSS name\n- cursor_label: short text shown near the cursor\n- cursor_size: dot radius in points (default=16)\n- cursor_opacity: 0.0–1.0 (default=0.85)\n\nMotion curve (Bezier path shape):\n- start_handle: departure control-point fraction [0,1]. Default 0.3\n- end_handle: arrival control-point fraction [0,1]. Default 0.3\n- arc_size: perpendicular deflection as fraction of path length [0,1]. Default 0.25\n- arc_flow: asymmetry [-1,1]; positive bulges toward destination. Default 0.0\n- spring: settle damping [0.3,1.0]; 1.0=no overshoot. Default 0.72\n- glide_duration_ms: fixed flight duration per move [50,5000]; omit for speed-based (the default)\n- dwell_after_click_ms: pause after click ripple [0,5000]. Default 80\n- idle_hide_ms: auto-hide delay [0,60000]; 0=never. Default 20000",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        arc_flow: {
          description: 'Asymmetry bias in [-1, 1]. Default 0.0.',
          type: 'number',
        },
        arc_size: {
          description:
            'Arc deflection as fraction of path length [0, 1]. Default 0.25.',
          type: 'number',
        },
        cursor_color: {
          description: "Hex color (e.g. '#00FFFF') or CSS color name.",
          type: 'string',
        },
        cursor_icon: {
          description: 'Built-in icon name or file path to PNG/SVG.',
          type: 'string',
        },
        cursor_id: {
          description: "Cursor instance name. Default: 'default'.",
          type: 'string',
        },
        cursor_label: {
          description: 'Short label near the cursor dot.',
          type: 'string',
        },
        cursor_opacity: {
          description: 'Opacity 0.0–1.0. Default: 0.85.',
          type: 'number',
        },
        cursor_size: {
          description: 'Dot radius in points. Default: 16.',
          type: 'number',
        },
        dwell_after_click_ms: {
          description: 'Pause after click ripple in ms. Default 80.',
          maximum: 5000,
          minimum: 0,
          type: 'number',
        },
        end_handle: {
          description: 'End-handle fraction in [0, 1]. Default 0.3.',
          type: 'number',
        },
        glide_duration_ms: {
          description:
            'Fixed flight duration per move in ms; omit for speed-based timing (the default).',
          maximum: 5000,
          minimum: 50,
          type: 'number',
        },
        idle_hide_ms: {
          description: 'Auto-hide delay in ms. 0 = never hide. Default 20000.',
          maximum: 60000,
          minimum: 0,
          type: 'number',
        },
        spring: {
          description: 'Settle damping in [0.3, 1.0]. Default 0.72.',
          type: 'number',
        },
        start_handle: {
          description: 'Start-handle fraction in [0, 1]. Default 0.3.',
          type: 'number',
        },
        turn_radius: {
          description:
            'Minimum turning radius of the glide path in points; smaller = tighter curves. Default 80.',
          maximum: 1000,
          minimum: 1,
          type: 'number',
        },
      },
      type: 'object',
    },
  },
  set_agent_cursor_style: {
    description:
      'Update the visual style of the agent cursor overlay.\n\n- gradient_colors: array of CSS hex strings (e.g. ["#FF0000","#0000FF"]) used as the arrow fill gradient from tip to tail. Empty array reverts to the default palette colours.\n- bloom_color: hex string for the radial halo/bloom behind the cursor (e.g. "#00FFFF"). Empty string reverts to the default.\n- image_path: path to a PNG, JPEG, SVG, or ICO file to use as the cursor icon instead of the default gradient arrow. Empty string reverts to the procedural arrow.\nAll parameters are optional; omit any you do not want to change.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        bloom_color: {
          description:
            "Hex bloom/halo colour (e.g. '#00FFFF'). '' = revert to default.",
          type: 'string',
        },
        cursor_id: {
          description: "Cursor instance. Default: 'default'.",
          type: 'string',
        },
        gradient_colors: {
          description:
            'CSS hex gradient stops tip→tail. [] = revert to default.',
          items: {
            type: 'string',
          },
          type: 'array',
        },
        image_path: {
          description:
            "Path to PNG/JPEG/SVG/ICO cursor image. '' = revert to arrow.",
          type: 'string',
        },
      },
      type: 'object',
    },
  },
  set_config: {
    description:
      'Update cua-driver-rs configuration. Changes to capture_mode and max_image_dimension take effect immediately. The experimental_pip keys are persisted to ~/.cua-driver/config.json and take effect on the next daemon restart (the PiP backend is initialised once at startup).',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        capture_mode: {
          description: 'Default capture mode for get_window_state.',
          enum: ['som', 'vision', 'ax'],
          type: 'string',
        },
        experimental_pip: {
          description:
            'Enable the experimental picture-in-picture preview window. Applies on next daemon restart.',
          type: 'boolean',
        },
        experimental_pip_geometry: {
          description:
            'PiP window size + optional position in `WxH` or `WxH+X+Y` form (e.g. `320x200+24+24`). Applies on next daemon restart.',
          type: 'string',
        },
        max_image_dimension: {
          description: 'Max dimension for screenshot resizing (0 = no limit).',
          type: 'integer',
        },
      },
      type: 'object',
    },
  },
  set_value: {
    description:
      'Set a value on a UI element. Two modes depending on element role:\n\n- **AXPopUpButton / select dropdown**: finds the child option whose title or value matches `value` (case-insensitive) and AXPresses it directly — the native macOS popup menu is never opened, so focus is never stolen. Use this for HTML <select> elements in Safari or any native NSPopUpButton.\n\n- **All other elements**: writes AXValue directly (sliders, steppers, date pickers, native text fields that expose settable AXValue).\n\nFor free-form text entry into web inputs, prefer `type_text_chars` which synthesises key events — AXValue writes are ignored by WebKit.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        element_index: {
          type: 'integer',
        },
        pid: {
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        value: {
          description:
            "New value. AX will coerce to the element's native type.",
          type: 'string',
        },
        window_id: {
          description:
            'CGWindowID for the window whose get_window_state produced the element_index.',
          type: 'integer',
        },
      },
      required: ['pid', 'window_id', 'element_index', 'value'],
      type: 'object',
    },
  },
  start_recording: {
    description:
      "Start trajectory recording. Every subsequent action-tool invocation (click, right_click, scroll, type_text, press_key, hotkey, set_value) writes a turn folder under `output_dir`:\n\n- `app_state.json` — post-action AX/UIA snapshot for the target pid.\n- `screenshot.png` — post-action per-window screenshot of the target's frontmost on-screen window.\n- `action.json` — tool name, full input arguments, result summary, pid, click point (when applicable), ISO-8601 timestamp.\n- `click.png` — for click-family actions only, `screenshot.png` with a red dot drawn at the click point.\n\nTurn folders are named `turn-00001/`, `turn-00002/`, etc.  Turn numbering restarts at 1 each time recording is (re-)started.\n\n**Video is off by default.** Pass `record_video: true` to also capture the main display to `<output_dir>/recording.mp4` (H.264 / 30 fps) for the lifetime of the session. The recording is torn down automatically when the MCP client disconnects.\n\n**macOS uses native ScreenCaptureKit** (in-process SCStream + SCRecordingOutput) so video inherits Cua Driver's own Screen Recording grant — no extra TCC prompt, no ffmpeg subprocess. Requires macOS 15.0+.\n\n**Windows + Linux use an ffmpeg subprocess** (`gdigrab` / `x11grab` + libx264). Requires ffmpeg on PATH (winget install Gyan.FFmpeg / apt install ffmpeg); when ffmpeg is missing or fails on startup the per-turn capture (screenshots + action.json) still runs and the session's `last_error` field carries the diagnostic.\n\nState persists for the life of the daemon / MCP session; a restart resets to disabled with no on-disk state. Call `stop_recording` to disable + finalize the mp4.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        output_dir: {
          description:
            'Absolute or ~-rooted directory where turn folders and (when enabled) the video file are written.',
          type: 'string',
        },
        record_video: {
          description:
            'Capture the main display to <output_dir>/recording.mp4. Default: false. Set to true to also capture the main display to recording.mp4 (otherwise only the per-turn screenshots + JSON are recorded). On macOS this uses native ScreenCaptureKit (no extra TCC prompt, macOS 15.0+); on Windows + Linux it requires ffmpeg on PATH.',
          type: 'boolean',
        },
      },
      required: ['output_dir'],
      type: 'object',
    },
  },
  start_session: {
    description:
      "Declare a session — a named, color-coded identity for THIS agent run. Pass a stable `session` id; the agent cursor, per-session config, and recording all key on it, and it follows the run across any apps/windows. The cursor's color is derived from the id, so distinct runs are visually distinct. A cursor is shown only for a declared session — call this (or pass `session` on your first action) to opt in. Idempotent: re-calling with the same id just refreshes its idle-TTL. End it with `end_session` (or let the idle-TTL reclaim it). Concurrent runs/subagents each pass their own `session` to get their own cursor.",
    parameterSchema: {
      additionalProperties: true,
      properties: {
        session: {
          description:
            'Stable session id for this run (e.g. "research-run-1").',
          type: 'string',
        },
      },
      required: ['session'],
      type: 'object',
    },
  },
  stop_recording: {
    description:
      "Stop trajectory recording. Disables further per-turn capture and, when video was enabled, gracefully terminates the ffmpeg subprocess so the mp4's moov atom is finalized (the file is playable). Calling stop on an already-stopped session is a no-op. The response carries `last_video_path` pointing at the finalized mp4 (when video was on).\n\nA manual `stop_recording` is **unconditional** — it stops whatever recording is active regardless of which session started it. Ownership-scoped teardown (so one MCP client disconnecting can't stop a recording a later client started) is handled by the daemon's `session_end` lifecycle signal, not by this tool.",
    parameterSchema: {
      additionalProperties: false,
      properties: {},
      type: 'object',
    },
  },
  type_text: {
    description:
      "Insert text into the target pid via `AXSetAttribute(kAXSelectedText)`. Works for standard Cocoa text fields and text views. No keystrokes are synthesized — special keys (Return / Escape / arrows) go through `press_key` / `hotkey`. For Chromium / Electron inputs that don't implement `kAXSelectedText`, the tool falls back to CGEvent character synthesis automatically.\n\nOptional `element_index` + `window_id` (from the last `get_window_state` snapshot) directs the write to a specific field. Without `element_index`, the write goes to the pid's currently focused element.",
    parameterSchema: {
      additionalProperties: false,
      properties: {
        delay_ms: {
          description:
            'Milliseconds between characters in the CGEvent fallback path. Default 30. Ignored when the AX path succeeds.',
          maximum: 200,
          minimum: 0,
          type: 'integer',
        },
        element_index: {
          description:
            'Element index from last get_window_state. Directs the write to a specific field. Requires window_id.',
          type: 'integer',
        },
        pid: {
          description: 'Target process ID.',
          type: 'integer',
        },
        session: {
          description:
            'Optional session id: declares/uses the agent cursor and per-session state for this run. The same id works over MCP, the CLI, or the raw socket, and follows the run across apps/windows. Omit to run cursor-less.',
          type: 'string',
        },
        text: {
          description: "Text to insert at the target's cursor.",
          type: 'string',
        },
        window_id: {
          description: 'CGWindowID. Required when element_index is used.',
          type: 'integer',
        },
      },
      required: ['pid', 'text'],
      type: 'object',
    },
  },
  zoom: {
    description:
      'Capture a cropped JPEG of a window region (x1,y1)–(x2,y2) in screenshot pixel coordinates, with 20% padding added on each side. The output image is at most 500 px wide.\n\nAfter a zoom, pass `from_zoom=true` to click/type_text to auto-translate coordinates back to full-window space.',
    parameterSchema: {
      additionalProperties: false,
      properties: {
        pid: {
          description:
            'Target pid — required for from_zoom click/type translation.',
          type: 'integer',
        },
        window_id: {
          description: 'CGWindowID from list_windows.',
          type: 'integer',
        },
        x1: {
          description: 'Left edge of region in screenshot pixels.',
          type: 'number',
        },
        x2: {
          description: 'Right edge of region in screenshot pixels.',
          type: 'number',
        },
        y1: {
          description: 'Top edge of region in screenshot pixels.',
          type: 'number',
        },
        y2: {
          description: 'Bottom edge of region in screenshot pixels.',
          type: 'number',
        },
      },
      required: ['window_id', 'x1', 'y1', 'x2', 'y2'],
      type: 'object',
    },
  },
};
