import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dialog, DialogContent, DialogHeader, DialogTitle, } from "@/components/ui/dialog";
import { CraftAgentsSymbol } from "./icons/CraftAgentsSymbol";
import { BRAND, APP_VERSION } from "@craft-agent/shared/branding";
import { ExternalLink } from "lucide-react";
export function AboutDialog({ open, onOpenChange }) {
    const version = APP_VERSION;
    return (_jsx(Dialog, { open: open, onOpenChange: onOpenChange, children: _jsxs(DialogContent, { className: "max-w-sm gap-0 p-0 overflow-hidden", children: [_jsx(DialogHeader, { className: "sr-only", children: _jsx(DialogTitle, { children: BRAND.appName }) }), _jsxs("div", { className: "flex flex-col items-center pt-8 pb-4 px-6", children: [_jsx(CraftAgentsSymbol, { className: "size-16 mb-4" }), _jsx("h2", { className: "text-lg font-semibold", children: BRAND.appName }), version && (_jsxs("p", { className: "text-xs text-muted-foreground mt-0.5", children: ["Version ", version] }))] }), BRAND.creditsEntries.length > 0 && (_jsxs("div", { className: "px-6 pb-6", children: [_jsx("p", { className: "text-xs text-muted-foreground text-center mb-3", children: BRAND.creditsShort }), _jsx("div", { className: "space-y-2", children: BRAND.creditsEntries.map((entry) => (_jsxs("a", { href: entry.url, target: "_blank", rel: "noopener noreferrer", className: "flex items-center justify-between rounded-lg border border-border/50 px-3 py-2.5 text-sm hover:bg-accent/5 transition-colors group", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("div", { className: "font-medium truncate", children: entry.name }), _jsx("div", { className: "text-xs text-muted-foreground truncate", children: entry.role })] }), _jsx(ExternalLink, { className: "size-3.5 text-muted-foreground shrink-0 ml-2 opacity-0 group-hover:opacity-100 transition-opacity" })] }, entry.name))) })] })), _jsx("div", { className: "border-t border-border/50 px-6 py-3", children: _jsx("p", { className: "text-[11px] text-muted-foreground text-center", children: BRAND.copyright }) })] }) }));
}
//# sourceMappingURL=AboutDialog.js.map