export default {
  '00-index': '索引 / 总览',
  '01-architecture': '01 · 系统架构',
  '02-serve-runtime': '02 · Serve 运行时',
  '03-acp-bridge': '03 · ACP Bridge',
  '04-permission-mediation': '04 · 多客户端权限协调',
  '05-mcp-transport-pool': '05 · Workspace MCP Transport 池',
  '06-mcp-budget-guardrails': '06 · MCP 工作区预算护栏',
  '07-workspace-filesystem': '07 · Workspace 文件系统边界',
  '08-session-lifecycle': '08 · Session 生命周期与身份',
  '09-event-schema': '09 · Typed Event Schema v1',
  '10-event-bus': '10 · SSE 事件总线与反压',
  '11-capabilities-versioning': '11 · 能力协商与协议版本',
  '12-auth-security': '12 · 认证与安全模型',
  '13-sdk-daemon-client': '13 · TypeScript SDK Daemon 客户端',
  '14-cli-tui-adapter': '14 · 共享 UI Transcript 层',
  '15-channel-adapters': '15 · Channel 适配器',
  '16-vscode-ide-adapter': '16 · VSCode IDE Daemon 适配器',
  '17-configuration': '17 · 配置参考',
  '18-error-taxonomy': '18 · 错误分类与修复',
  '19-observability': '19 · 可观测性与调试',
  '20-quickstart-operations': '20 · 快速上手与运维手册',
};
