export default {
  '00-index': 'Index / Overview',
  '01-architecture': '01 · System Architecture',
  '02-serve-runtime': '02 · Serve Runtime',
  '03-acp-bridge': '03 · ACP Bridge',
  '04-permission-mediation': '04 · Permission Mediation',
  '05-mcp-transport-pool': '05 · MCP Transport Pool',
  '06-mcp-budget-guardrails': '06 · MCP Budget Guardrails',
  '07-workspace-filesystem': '07 · Workspace File System',
  '08-session-lifecycle': '08 · Session Lifecycle & Identity',
  '09-event-schema': '09 · Typed Event Schema v1',
  '10-event-bus': '10 · SSE Event Bus & Backpressure',
  '11-capabilities-versioning': '11 · Capabilities & Protocol Versioning',
  '12-auth-security': '12 · Auth & Security Model',
  '13-sdk-daemon-client': '13 · TypeScript SDK Daemon Client',
  '14-cli-tui-adapter': '14 · Shared UI Transcript Layer',
  '15-channel-adapters': '15 · Channel Adapters',
  '16-vscode-ide-adapter': '16 · VS Code IDE Daemon Adapter',
  '17-configuration': '17 · Configuration Reference',
  '18-error-taxonomy': '18 · Error Taxonomy & Remediation',
  '19-observability': '19 · Observability & Debugging',
  '20-quickstart-operations': '20 · Quickstart & Operations',
};
