import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import * as React from 'react';
import { useTranslation } from 'react-i18next';
import { Search, X } from 'lucide-react';
import { Spinner } from '@craft-agent/ui';
export function SessionSearchHeader({ searchQuery, onSearchChange, onSearchClose, onKeyDown, onFocus, onBlur, isSearching = false, isUnavailable = false, resultCount, exceededLimit = false, inputRef, placeholder = 'Search titles and content...', readOnly = false, }) {
    const { t } = useTranslation();
    return (_jsxs("div", { className: "shrink-0 px-2 pt-2 pb-1.5 border-b border-border/50", children: [_jsxs("div", { className: "relative rounded-[8px] shadow-minimal bg-muted/50 has-[:focus-visible]:bg-background", children: [_jsx(Search, { className: "absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-muted-foreground" }), _jsx("input", { ref: inputRef, type: "text", value: searchQuery, onChange: (e) => onSearchChange?.(e.target.value), onKeyDown: onKeyDown, onFocus: onFocus, onBlur: onBlur, readOnly: readOnly, placeholder: placeholder, className: "w-full h-8 pl-8 pr-8 text-sm bg-transparent border-0 rounded-[8px] outline-none focus-visible:ring-0 focus-visible:outline-none placeholder:text-muted-foreground/50" }), onSearchClose && (_jsx("button", { onClick: onSearchClose, className: "absolute right-2 top-1/2 -translate-y-1/2 p-0.5 hover:bg-foreground/10 rounded", title: t("session.closeSearch"), children: _jsx(X, { className: "h-3.5 w-3.5 text-muted-foreground" }) }))] }), searchQuery.length >= 2 && (_jsx("div", { className: "px-2 pt-2.5 flex items-center gap-1.5 text-xs text-muted-foreground", children: isSearching ? (_jsxs(_Fragment, { children: [_jsx(Spinner, { className: "text-[9px] text-foreground/50" }), _jsx("span", { children: t('common.loading') })] })) : isUnavailable ? (_jsx("span", { className: "text-destructive/70", children: t('session.searchUnavailable') })) : (_jsx("span", { children: t('session.results', { count: exceededLimit ? '100+' : (resultCount ?? 0) }) })) }))] }));
}
//# sourceMappingURL=SessionSearchHeader.js.map