/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */
import type { Content } from '@google/genai';
import type { HistoryGap } from '../utils/conversation-chain.js';
import type { ChatRecord, TitleSource } from './chatRecordingService.js';
import type { FileHistorySnapshot } from './fileHistoryService.js';
import { type RebuiltSessionArtifactSnapshot } from './session-artifact-persistence.js';
import {
  SessionWriterLease,
  type SessionWriterProcessKind,
} from './session-writer-lease.js';
/**
 * Session item for list display.
 * Contains essential info extracted from the first record of a session file.
 */
export interface SessionListItem {
  /** Unique session identifier */
  sessionId: string;
  /** Working directory at session start */
  cwd: string;
  /** ISO 8601 timestamp when session started */
  startTime: string;
  /** File modification time (used for ordering and pagination) */
  mtime: number;
  /** First user prompt text (truncated for display) */
  prompt: string;
  /** Git branch at session start, if available */
  gitBranch?: string;
  /** Full path to the session file */
  filePath: string;
  /**
   * Number of unique-UUID user/assistant messages, when known. Listing
   * does NOT compute this — counting requires a full readline pass over
   * the JSONL and was the dominant cost of `listSessions` once a project
   * accumulated many sessions. Use {@link SessionService.countSessionMessages}
   * (or compute from the resumed conversation) when the count is needed.
   */
  messageCount?: number;
  /** Custom title set via /rename or auto-generated by the title service, if any */
  customTitle?: string;
  /**
   * Source of {@link customTitle}. `undefined` on legacy records without a
   * source field — consumers should treat `undefined` and `'manual'` the
   * same way for display (full-contrast). UI affordances like dimming are
   * reserved for `'auto'` so users can tell a model guess from a name they
   * chose.
   */
  titleSource?: TitleSource;
  /** Id of the session that spawned this one (via `create_sub_session`), if
   * any. Read from the transcript's `parent_session` record. Absent for a
   * top-level session. */
  parentSessionId?: string;
  /** Immutable creator attribution read from `session_source`. */
  sourceType?: string;
  /** Optional source-specific identifier paired with `sourceType`. */
  sourceId?: string;
  /** True when the item was read from the archive directory. */
  isArchived?: boolean;
}
export type SessionArchiveState = 'active' | 'archived';
export type SessionLocation = SessionArchiveState | 'conflict' | undefined;
/**
 * Pagination options for listing sessions.
 */
export interface ListSessionsOptions {
  /**
   * Cursor for pagination (mtime of the last item from previous page).
   * Items with mtime < cursor will be returned.
   * If undefined, starts from the most recent.
   */
  cursor?: number;
  /**
   * Maximum number of items to return.
   * @default 20
   */
  size?: number;
  /**
   * Which session directory to list.
   * @default 'active'
   */
  archiveState?: SessionArchiveState;
  /** Aborts an in-progress catalog scan. */
  signal?: AbortSignal;
}
/**
 * Result of listing sessions with pagination info.
 */
export interface ListSessionsResult {
  /** Session items for this page */
  items: SessionListItem[];
  /**
   * Cursor for next page (mtime of last item).
   * Undefined if no more items.
   */
  nextCursor?: number;
  /** Whether there are more items after this page */
  hasMore: boolean;
}
/**
 * Aggregate persisted-session counts for a workspace.
 *
 * Built by scanning local JSONL files. This is intentionally separate from
 * {@link listSessions} so paginated list callers are not forced into a full
 * disk walk.
 */
export interface SessionInfoCounts {
  /** Persisted active (non-archived) sessions belonging to this project. */
  active: number;
  /** Persisted archived sessions belonging to this project. */
  archived: number;
  /** `active + archived`. */
  total: number;
  /**
   * True when the scan could not classify every candidate session file, so
   * counts may be lower than the true population.
   */
  truncated: boolean;
}
/**
 * Result of removing multiple sessions.
 */
export interface RemoveSessionsResult {
  removed: string[];
  notFound: string[];
  errors: Array<{
    sessionId: string;
    error: Error;
  }>;
}
export interface ArchiveSessionsResult {
  archived: string[];
  alreadyArchived: string[];
  notFound: string[];
  errors: Array<{
    sessionId: string;
    error: Error;
  }>;
}
export interface ArchiveSessionsOptions {
  knownLocation?: 'active';
}
export interface UnarchiveSessionsResult {
  unarchived: string[];
  alreadyActive: string[];
  notFound: string[];
  errors: Array<{
    sessionId: string;
    error: Error;
  }>;
}
export interface UnarchiveSessionsOptions {
  knownLocation?: 'archived';
}
export interface SessionServiceOptions {
  onWarning?: (message: string) => void;
  runtimeBaseDir?: string;
}
/**
 * Complete conversation reconstructed from ChatRecords.
 * Used for resuming sessions and API compatibility.
 */
export interface ConversationRecord {
  sessionId: string;
  projectHash: string;
  startTime: string;
  lastUpdated: string;
  /** Messages in chronological order (reconstructed from tree) */
  messages: ChatRecord[];
}
/**
 * Data structure for resuming an existing session.
 */
export interface ResumedSessionData {
  conversation: ConversationRecord;
  filePath: string;
  /** UUID of the last completed message - new messages should use this as parentUuid */
  lastCompletedUuid: string | null;
  /** Deserialized file history snapshots for resume (enables /rewind across sessions) */
  fileHistorySnapshots?: FileHistorySnapshot[];
  /** Persisted session artifact metadata reconstructed from JSONL records. */
  artifactSnapshot?: RebuiltSessionArtifactSnapshot;
  /**
   * Breaks in the persisted parentUuid chain that were detected during
   * reconstruction (an earlier segment of history was physically lost and could
   * not be recovered). Lets the surface render a visible gap divider. Undefined
   * when the chain was intact.
   */
  historyGaps?: HistoryGap[];
}
/**
 * Maximum character length for a session custom title.
 * Shared across CLI, WebUI, VSCode, and ACP.
 */
export declare const SESSION_TITLE_MAX_LENGTH = 200;
/**
 * Service for managing chat sessions.
 *
 * This service handles:
 * - Listing sessions with pagination (ordered by mtime)
 * - Loading full session data for resumption
 * - Removing sessions
 *
 * Sessions are stored as JSONL files, one per session.
 * File location: ~/.qwen/tmp/<project_id>/chats/
 */
export declare class SessionService {
  private readonly storage;
  private readonly projectHash;
  private readonly projectRoot;
  private readonly onWarning;
  constructor(cwd: string, options?: SessionServiceOptions);
  /** The workspace root this service is bound to (the cwd it was constructed
   * with). Lets callers that already hold a service — e.g. the session
   * archive/delete choke points — reach per-project state such as the durable
   * scheduled-tasks file without re-plumbing the workspace path. */
  getProjectRoot(): string;
  acquireSessionWriterLease(
    sessionId: string,
    options: {
      processKind: SessionWriterProcessKind;
      qwenVersion?: string | null;
      reclaimPolicy: 'local' | 'never';
    },
  ): Promise<SessionWriterLease>;
  private warn;
  private getChatsDir;
  private getArchiveChatsDir;
  private getChatsDirForState;
  private getSessionFilePath;
  private getWorktreeSessionPathForState;
  private sessionBelongsToCurrentProject;
  /**
   * Returns the absolute path to the sidecar JSON file that stores
   * worktree session state for the given session id. The file may not
   * exist yet — consumers must handle ENOENT as "no active worktree".
   */
  getWorktreeSessionPath(sessionId: string): string;
  getWorktreeSessionPathForArchiveState(
    sessionId: string,
    state: SessionArchiveState,
  ): string;
  private readProjectSessionHead;
  /**
   * Reads the persisted `parentSessionId` for a single session (active or
   * archived), or undefined when it has no parent. Used to re-seed a live entry
   * on restore/resume so a restored sub-session's status still reports its
   * lineage after a daemon restart. Best-effort: a read failure returns
   * undefined rather than throwing — a missing link must never fail a restore.
   */
  readParentSessionId(sessionId: string): Promise<string | undefined>;
  /** Reads immutable creation metadata for an active or archived session. */
  readCreationMetadata(sessionId: string): Promise<{
    parentSessionId?: string;
    sourceType?: string;
    sourceId?: string;
  }>;
  getSessionLocation(sessionId: string): Promise<SessionLocation>;
  /**
   * Finds a persisted session whose UUID filename differs only by case.
   * Legacy CLI sessions may have been written with `uuidgen`'s uppercase
   * spelling, while daemon-facing caller IDs are canonicalized to lowercase.
   */
  findSessionIdIgnoringCase(sessionId: string): Promise<string | undefined>;
  private removeFileIfExists;
  private removeWorktreeSidecars;
  private removeFileHistoryBackups;
  private removeSessionOrganization;
  private removeSessionOrganizations;
  private moveOptionalFile;
  private sessionFileMoveError;
  /**
   * Reads the session title from a JSONL file.
   *
   * Delegates to {@link readLastJsonStringFieldSync}, which scans the tail
   * window first (fast path; almost always hits because finalize() re-appends
   * the title on every lifecycle event) and falls back to a bounded head
   * window when the tail has no match. The `custom_title` line-marker guards
   * against false matches from user content that happens to include a
   * `customTitle` field.
   */
  private readSessionTitleFromFile;
  /**
   * Reads both the custom title and its source from a session file in a
   * single pass — the helper extracts both fields from the same matching
   * `custom_title` line, so the pair is always consistent (never one field
   * from an old record and another from a new one).
   *
   * `titleSource` is absent on legacy records written before the field was
   * introduced — callers treat `undefined` as equivalent to `'manual'` so a
   * user's pre-upgrade rename is never displayed as if it were auto-generated.
   */
  private readSessionTitleInfoFromFile;
  /**
   * Extracts the `parent_session` record's `parentSessionId` from records
   * ALREADY read for the listing (the first {@link MAX_PROMPT_SCAN_LINES}), or
   * undefined when the session has no parent. The record is written once right
   * after the sub-session is created — before any prompt — so it is reliably
   * within that window. No extra file open, unlike the title (which re-anchors
   * at EOF and needs its own tail-then-head scan).
   */
  private extractCreationMetadataFromRecords;
  /**
   * Public accessor: returns both the current custom title and its source
   * for a given session. Used by `ChatRecordingService` on resume to
   * preserve the persisted `titleSource` rather than defaulting to manual.
   *
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  getSessionTitleInfo(sessionId: string): {
    title?: string;
    source?: TitleSource;
  };
  /**
   * Reads the UUID of the last record in a session JSONL file.
   * Uses a tail-read strategy for efficiency.
   *
   * Each physical line is routed through `jsonl.parseLineTolerant` so a
   * `}{`-glued tail line (#3606 corruption shape) still yields its records
   * instead of being silently skipped — otherwise `renameSession` would set
   * `custom_title.parentUuid` to a stale uuid and `reconstructHistory` would
   * truncate the chain on resume.
   */
  private readLastRecordUuid;
  /**
   * Extracts the first user prompt text from a Content object.
   */
  private extractPromptText;
  /**
   * Finds the first available prompt text by scanning the first N records,
   * preferring user messages. Returns an empty string if none found.
   */
  private extractFirstPromptFromRecords;
  private truncatePromptForDisplay;
  /**
   * Counts unique user/assistant message UUIDs in a session file by
   * streaming the JSONL line-by-line. Each physical line is routed
   * through `jsonl.parseLineTolerant` so a `}{`-glued line (#3606
   * corruption shape) still contributes both records, instead of being
   * silently dropped.
   *
   * Project-scoped: returns 0 if the file's first record belongs to a
   * different project. Sibling public methods (deleteSession,
   * renameSession, loadSession) apply the same first-record cwd check;
   * mirroring it here keeps lazy-count callers from accidentally
   * counting a session that lives in the shared chats directory but
   * belongs to another project.
   *
   * This is intentionally NOT called from {@link listSessions} or
   * {@link findSessionsByTitle} — it would be O(total bytes on disk) per
   * picker open, dominating wall time once a project accumulates dozens
   * of multi-MB sessions. Call this lazily, only when a specific
   * session's message count is about to be displayed (e.g., from a
   * preview panel) or computed from a resumed conversation.
   *
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  countSessionMessages(sessionId: string): Promise<number>;
  private countSessionMessagesFromPath;
  /**
   * Lists sessions for the current project with pagination.
   *
   * Sessions are ordered by file modification time (most recent first).
   * Uses cursor-based pagination with mtime as the cursor.
   *
   * Only reads the first line of each JSONL file for efficiency.
   * Files are filtered by UUID pattern first, then by project hash.
   *
   * @param options Pagination options
   * @returns Paginated list of sessions
   */
  listSessions(options?: ListSessionsOptions): Promise<ListSessionsResult>;
  /**
   * Counts persisted sessions for this project by scanning the active and
   * archived chats directories.
   *
   * Same disk-walk shape as {@link findSessionTitlesByPrefix} /
   * {@link findSessionsByTitle}: `readdir` the chats dir, cap at the
   * file-processing safety limit, then read only the first JSONL record for
   * project membership. Title/prompt/message hydration is skipped entirely.
   *
   * Still an O(n) disk walk — callers (and HTTP clients of
   * `GET .../session-info`) must not poll this in a tight loop.
   */
  getSessionInfoCounts(): Promise<SessionInfoCounts>;
  private countSessionsInState;
  /**
   * Reads all records from a session file.
   */
  private readAllRecords;
  /**
   * Reconstructs a linear conversation from tree-structured records.
   *
   * Delegates validation, parentUuid walking, and fragment aggregation to the
   * shared transcript record preparation module. With
   * `detectGaps`, a walk that stops on a physically-missing parent records the
   * break in the returned `gaps` (see {@link HistoryGap}) so the surface can
   * mark it — the earlier records are NOT reconstructed (reconnecting them
   * could resurrect turns the user rewound away). Without `detectGaps` the
   * result is identical to the historical walk.
   */
  private reconstructHistory;
  /**
   * Loads a session by its session ID.
   * Reconstructs the full conversation from tree-structured records.
   *
   * @param sessionId The session ID to load
   * @returns Session data for resumption, or undefined if not found
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  loadSession(sessionId: string): Promise<ResumedSessionData | undefined>;
  /**
   * Reads an archived session without changing its archive state.
   * Daemon load/resume paths must continue to use {@link loadSession}.
   */
  loadArchivedSession(
    sessionId: string,
    options: {
      maxBytes: number;
    },
  ): Promise<ResumedSessionData | undefined>;
  private loadSessionFromState;
  /**
   * Removes a session by its session ID.
   *
   * @param sessionId The session ID to remove
   * @returns true if removed, false if not found
   */
  removeSession(sessionId: string): Promise<boolean>;
  /**
   * Usage salvage wrapper enforcing the "never blocks deletion" contract at
   * the call site: persistUsageBeforeTranscriptDeletion catches its own
   * errors, but this second layer keeps the guarantee structural rather
   * than an implementation detail of another module.
   */
  private salvageUsageBestEffort;
  private removeSessionFiles;
  archiveSessions(
    sessionIds: string[],
    options?: ArchiveSessionsOptions,
  ): Promise<ArchiveSessionsResult>;
  unarchiveSessions(
    sessionIds: string[],
    options?: UnarchiveSessionsOptions,
  ): Promise<UnarchiveSessionsResult>;
  /**
   * Removes multiple sessions in one call.
   *
   * Each session is processed independently — a failure on one does not
   * abort the rest. Sessions that don't exist (or belong to a different
   * project) are reported in {@link notFound}; thrown filesystem
   * errors are surfaced per-id in {@link errors} so callers can decide
   * whether to retry.
   *
   * @param sessionIds IDs to remove. Duplicates are de-duplicated.
   * @returns Per-id outcomes: which were removed, which were not found,
   *   and which threw an error.
   */
  removeSessions(sessionIds: string[]): Promise<RemoveSessionsResult>;
  /**
   * Renames a session by appending a custom_title system record to its JSONL file.
   *
   * @param sessionId The session ID to rename
   * @param title The new custom title
   * @param titleSource Where the title came from. Defaults to `'manual'` so
   *   existing callers are unchanged — pass `'auto'` only for titles produced
   *   by the auto-title generator.
   * @returns true if renamed successfully, false if session not found
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  renameSession(
    sessionId: string,
    title: string,
    titleSource?: TitleSource,
  ): Promise<boolean>;
  /**
   * Forks a session to a new sessionId.
   *
   * Reads the source JSONL into memory, reconstructs the active record chain,
   * rewrites every record's `sessionId` to `newSessionId`, stamps `cwd` to this
   * service's project root, rebuilds the `parentUuid` chain so the fork is a
   * linear continuation, stamps `forkedFrom: { sessionId, messageUuid }` on
   * every copied record for audit, and writes the result to `<newId>.jsonl`.
   *
   * Mirrors Claude Code's `/branch` storage model: full in-memory copy + per-
   * message forkedFrom (see claude-code/src/commands/branch/branch.ts).
   *
   * The source file is not modified.
   *
   * @throws If source does not exist, source is empty, source belongs to a
   *   different project, or the target file already exists.
   * @remarks Only checks active source sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  forkSession(
    sourceSessionId: string,
    newSessionId: string,
    options?: {
      source?: {
        sourceType: string;
        sourceId?: string;
      };
    },
  ): Promise<{
    filePath: string;
    copiedCount: number;
  }>;
  /**
   * Gets the custom title for a session by reading from its JSONL file.
   *
   * @param sessionId The session ID to look up
   * @returns The custom title, or undefined if none set
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  getSessionTitle(sessionId: string): string | undefined;
  /**
   * Finds sessions by custom title.
   * Returns all matching sessions ordered by most recent first.
   *
   * @param title The custom title to search for (case-insensitive exact match)
   * @returns Array of matching session list items
   * @remarks Only searches active sessions. Archived title search is not
   * supported.
   */
  findSessionsByTitle(title: string): Promise<SessionListItem[]>;
  /**
   * Returns the customTitles in this project that start with `prefix`
   * (case-insensitive). Single project-wide scan — meant to replace
   * repeated `findSessionsByTitle()` probes when the caller needs to
   * pick the first free `(Branch N)` slot in memory.
   *
   * Skips the heavy hydration steps (message count, prompt extraction)
   * that `findSessionsByTitle` does — collision lookup only needs the
   * title and a project filter, so we read the first record only when
   * the title actually matches the prefix.
   *
   * @param prefix Case-insensitive title prefix to match.
   */
  findSessionTitlesByPrefix(prefix: string): Promise<string[]>;
  /**
   * Loads the most recent session for the current project.
   * Combines listSessions and loadSession for convenience.
   *
   * @returns Session data for resumption, or undefined if no sessions exist
   */
  loadLastSession(): Promise<ResumedSessionData | undefined>;
  /**
   * Checks if a session exists by its session ID.
   *
   * @param sessionId The session ID to check
   * @returns true if session exists and belongs to current project
   * @remarks Only checks active sessions. Use `getSessionLocation()` or
   * `sessionExistsInAnyState()` for archive-aware lookups.
   */
  sessionExists(
    sessionId: string,
    options?: {
      signal?: AbortSignal;
    },
  ): Promise<boolean>;
  sessionExistsInAnyState(sessionId: string): Promise<boolean>;
}
/**
 * Options for building API history from conversation.
 */
export interface BuildApiHistoryOptions {
  /**
   * Whether to strip thought parts from the history.
   * Thought parts are content parts that have `thought: true`.
   * Keeping thoughts ensures `reasoning_content` from reasoning models
   * (e.g. DeepSeek) is properly passed back in subsequent API calls.
   * @default false
   */
  stripThoughtsFromHistory?: boolean;
}
/**
 * Builds the model-facing chat history (Content[]) from a reconstructed
 * conversation. This keeps UI history intact while applying chat compression
 * checkpoints for the API history used on resume.
 *
 * Strategy:
 * - Find the latest system/chat_compression record (if any).
 * - Use its compressedHistory snapshot as the base history.
 * - Append all messages after that checkpoint (skipping system records).
 * - If no checkpoint exists, return the linear message list (message field only).
 */
export declare function buildApiHistoryFromConversation(
  conversation: ConversationRecord,
  options?: BuildApiHistoryOptions,
): Content[];
/**
 * Replays stored UI telemetry events to rebuild metrics when resuming a session.
 * Also restores the last prompt token count from the best available source.
 */
export declare function replayUiTelemetryFromConversation(
  conversation: ConversationRecord,
  sessionId?: string,
): ResumeTokenCounts | undefined;
export interface ResumeTokenCounts {
  promptTokenCount: number;
  outputTokenCount: number;
  isEstimated: boolean;
}
/**
 * Returns the best available prompt token count for resuming telemetry.
 * Walks backward through messages and returns the first valid value:
 * - The latest assistant's non-zero usage (promptTokenCount ?? totalTokenCount).
 * - The most recent chat compression checkpoint's newTokenCount.
 */
export declare function getResumePromptTokenCount(
  conversation: ConversationRecord,
): number | undefined;
/**
 * Returns the prompt and previous-response output token counts used to seed a
 * resumed chat. The prompt count restores the context anchor; the output
 * count preserves the output tokens appended after that prompt count was
 * reported, matching steady-state prompt estimation on the next send.
 */
export declare function getResumeTokenCounts(
  conversation: ConversationRecord,
): ResumeTokenCounts | undefined;
export declare function computeUniqueBranchTitle(
  baseName: string,
  sessionService: SessionService,
): Promise<string>;
