/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 *
 * AUTO approval mode LLM classifier.
 *
 * Two-stage flow:
 *   Stage 1 (fast):  shouldBlock-only output, max_tokens=32, thinking off.
 *                    Allow path returns immediately (~300ms).
 *   Stage 2 (review): full output { thinking, shouldBlock, reason },
 *                     max_tokens=4096, thinking on. Reviews stage-1 blocks
 *                     to reduce false positives.
 *
 * Fail-closed: any non-abort failure (API error, timeout, schema failure,
 * context overflow) returns shouldBlock=true with unavailable=true.
 */
import type { Content } from '@google/genai';
import type { Config } from '../config/config.js';
/** Stage-1 timeout: fast model p99 is ~1.5s; 3s catches stuck cases. */
export declare const STAGE1_TIMEOUT_MS = 3000;
/** Stage-2 timeout: thinking takes longer; 10s caps infrastructure failure. */
export declare const STAGE2_TIMEOUT_MS = 10000;
/** Token usage attributed to a single classifier call. */
export interface ClassifierUsage {
    inputTokens: number;
    outputTokens: number;
}
/** Input to the classifier orchestrator. */
export interface ClassifierInput {
    toolName: string;
    toolParams: Record<string, unknown>;
    /** Main session history. Transcript construction strips assistant text and
     *  tool results — see classifier-transcript module. Forwarded by reference
     *  (read-only). */
    messages: readonly Content[];
    config: Config;
    signal: AbortSignal;
}
/** Outcome of a classifier call. */
export interface ClassifierResult {
    /** True when the action should be blocked. */
    shouldBlock: boolean;
    /**
     * One short sentence shown to the user on block (and surfaced in the
     * tool error returned to the main LLM). Empty when `shouldBlock=false`.
     */
    reason: string;
    /** Stage-2 thinking content, when available. Not displayed to user. */
    thinking?: string;
    /** Model name actually used for the call (typically the fast model). */
    model: string;
    /** Wall-clock latency in milliseconds. */
    durationMs: number;
    /** Per-stage token usage; undefined when classifier was unavailable. */
    usage?: ClassifierUsage;
    /**
     * True when the classifier could not respond (API error, timeout,
     * schema failure, context overflow). The caller MUST treat this as a
     * block but distinguish it from a policy block in UI/telemetry — it
     * represents infrastructure failure rather than policy judgement.
     */
    unavailable?: boolean;
    /** Which stage produced the final verdict. */
    stage: 'fast' | 'thinking';
}
/**
 * Evaluate a pending tool call through the two-stage classifier.
 *
 * Returns a `ClassifierResult` describing the verdict. Throws `AbortError`
 * only when the user-supplied `input.signal` is aborted; all other failures
 * are converted into `unavailable=true` block results (fail-closed).
 */
export declare function classifyAction(input: ClassifierInput): Promise<ClassifierResult>;
/**
 * The classifier's `reason` string is generated by a separate LLM and gets
 * interpolated into the tool error message that the main model reads next.
 * Strip pseudo-tags and clamp the length so a hostile classifier output
 * cannot impersonate a system message or stage a multi-paragraph injection
 * against the main agent.
 *
 * Exposed so callers that interpolate `decision.reason` into user-visible
 * or model-visible strings get a defended version.
 */
export declare function sanitizeClassifierReason(raw: string): string;
export type { Content };
