/**
 * @license
 * Copyright 2025 Qwen Team
 * SPDX-License-Identifier: Apache-2.0
 */

export {
  DaemonClient,
  DaemonHttpError,
  DaemonPendingPromptLimitError,
  isDaemonTurnError,
  isNonBlockingAccepted,
  matchTurnEvent,
  type CreateSessionRequest,
  type DaemonClientOptions,
  type DaemonTurnError,
  type NonBlockingPromptAccepted,
  type PromptRequest,
  type RestoreSessionRequest,
  type SubscribeOptions,
} from './DaemonClient.js';
// Transport abstraction layer
export { DaemonTransportClosedError } from './DaemonTransport.js';
export type {
  DaemonTransport,
  DaemonTransportFetchOptions,
  DaemonTransportSubscribeOptions,
  DaemonTransportType,
} from './DaemonTransport.js';
export type { RestSseTransport } from './RestSseTransport.js';
// negotiateTransport + ACP transport classes live in their own files to
// break the static import chain from this barrel, keeping the browser
// bundle under budget.  Monorepo consumers import from source paths:
//   import { negotiateTransport } from '../../sdk-typescript/src/daemon/negotiateTransport.js';
//   import { AcpWsTransport }     from '../../sdk-typescript/src/daemon/AcpWsTransport.js';
//   import { AcpHttpTransport }   from '../../sdk-typescript/src/daemon/AcpHttpTransport.js';
//   import { AutoReconnectTransport } from '../../sdk-typescript/src/daemon/AutoReconnectTransport.js';
// Deep package exports are intentionally omitted: the SDK barrel does not
// re-export these classes, and the package's `files` field ships only
// `dist/` which does not include per-module entry points for them.
export type { NegotiateTransportOptions } from './negotiateTransport.js';
export type { JsonRpcNotification } from './AcpEventDenormalizer.js';
export type { TransportFactory } from './AutoReconnectTransport.js';
export {
  DaemonAuthFlow,
  DEVICE_FLOW_EXPIRY_GRACE_MS,
  type AwaitCompletionOptions,
  type DaemonAuthFlowHandle,
} from './DaemonAuthFlow.js';
export {
  DaemonSessionClient,
  type DaemonReplaySnapshot,
  type DaemonSessionClientOptions,
  type DaemonSessionSubscribeOptions,
} from './DaemonSessionClient.js';
export {
  asKnownDaemonEvent,
  DAEMON_KNOWN_EVENT_TYPE_VALUES,
  createDaemonAuthState,
  createDaemonSessionViewState,
  isDaemonEventType,
  isKnownDaemonEvent,
  // Re-export the workspace-scoped budget event helper. Previously
  // the event JSDoc told consumers to use this helper to branch on
  // `scope === 'workspace'`, but the function lived in `events.ts`
  // and was never added to this barrel — SDK consumers had no public
  // import path. Now locked down by `daemon-public-surface.test.ts`.
  isWorkspaceScopedBudgetEvent,
  reduceDaemonAuthEvent,
  reduceDaemonAuthEvents,
  reduceDaemonSessionEvent,
  reduceDaemonSessionEvents,
} from './events.js';
export { parseSseStream, SseFramingError } from './sse.js';
export {
  appendLocalUserTranscriptMessage,
  createDaemonToolPreview,
  createDaemonTranscriptState,
  createDaemonTranscriptStore,
  DAEMON_GOAL_STATUS_SENTINEL_PREFIX,
  DAEMON_PLAN_TOOL_CALL_ID,
  daemonBlockToHtml,
  daemonBlockToMarkdown,
  daemonBlockToPlainText,
  daemonToolPreviewToMarkdown,
  daemonUiEventToTerminalText,
  extractContentPart,
  formatBlockTimestamp,
  getOutputText as getDaemonUiOutputText,
  getSessionUpdatePayload,
  isDaemonUiSensitiveKey,
  isSubagentChildBlock,
  normalizeDaemonEvent,
  redactDaemonUiSensitiveFields,
  rebuildDaemonTranscriptBlockIndex,
  reduceDaemonTranscriptEvents,
  runAdapterConformanceSuite,
  sanitizeTerminalText as sanitizeDaemonTerminalText,
  selectApprovalMode,
  selectCurrentTool,
  selectLastFollowupSuggestion,
  selectPendingPermissionBlocks,
  selectSubagentChildBlocks,
  selectToolProgress,
  selectTranscriptBlocks,
  selectTranscriptBlocksOrderedByEventId,
  stringifyJson as stringifyDaemonUiJson,
  stripOscSequences as stripDaemonOscSequences,
  transcriptBlockToTerminalText,
  DAEMON_UI_CONFORMANCE_FIXTURES,
} from './ui/index.js';
export type {
  DaemonRenderOptions,
  DaemonHtmlRenderOptions,
  DaemonUiContentPart,
  DaemonUiAdapterUnderTest,
  DaemonUiConformanceFixture,
  ConformanceFailure,
  ConformanceSuiteResult,
  RunConformanceOptions,
} from './ui/index.js';
export type {
  DaemonShellTranscriptBlock,
  DaemonUserShellTranscriptBlock,
  DaemonPermissionTranscriptBlock,
  DaemonStatusTranscriptBlock,
  DaemonTextTranscriptBlock,
  DaemonToolPreview,
  DaemonToolTranscriptBlock,
  DaemonTranscriptBlock,
  DaemonTranscriptBlockKind,
  DaemonTranscriptQuestion,
  DaemonTranscriptQuestionOption,
  DaemonTranscriptReducerOptions,
  DaemonTranscriptSidechannelState,
  DaemonTranscriptState,
  DaemonTranscriptStore,
  DaemonUiAssistantDoneEvent,
  DaemonUiAuthDeviceFlowAuthorizedEvent,
  DaemonUiAuthDeviceFlowCancelledEvent,
  DaemonUiAuthDeviceFlowEvent,
  DaemonUiAuthDeviceFlowFailedEvent,
  DaemonUiAuthDeviceFlowStartedEvent,
  DaemonUiAuthDeviceFlowThrottledEvent,
  DaemonUiErrorEvent,
  DaemonUiEvent,
  DaemonUiEventBase,
  DaemonUiEventType,
  DaemonUiMcpBudgetWarningEvent,
  DaemonUiMcpChildRefusedEvent,
  DaemonUiMcpServerRestartedEvent,
  DaemonUiMcpServerRestartRefusedEvent,
  DaemonUiModelChangedEvent,
  DaemonUiPermissionOption,
  DaemonUiPermissionRequestEvent,
  DaemonUiPermissionResolvedEvent,
  DaemonUiSessionActions,
  DaemonUiSessionApprovalModeChangedEvent,
  DaemonUiSessionAvailableCommandsEvent,
  DaemonUiSessionMetadataChangedEvent,
  DaemonUiShellOutputEvent,
  DaemonUiStateResyncRequiredEvent,
  DaemonUiReplayCompleteEvent,
  DaemonUiPromptCancelledEvent,
  DaemonUiFollowupSuggestionEvent,
  DaemonUiStatusEvent,
  DaemonUiTextEvent,
  DaemonUiToolProvenance,
  DaemonUiToolUpdateEvent,
  DaemonUiWorkspaceAgentChangedEvent,
  DaemonUiWorkspaceInitializedEvent,
  DaemonUiWorkspaceMemoryChangedEvent,
  DaemonUiWorkspaceToolToggledEvent,
  NormalizeDaemonEventOptions,
} from './ui/index.js';
export {
  DAEMON_APPROVAL_MODES,
  DAEMON_ERROR_KINDS,
  DaemonCapabilityMissingError,
  isDaemonContentHash,
  requireWorkspaceCwd,
} from './types.js';
export type {
  DaemonAgentChangedData,
  DaemonAgentChangedEvent,
  DaemonApprovalModeChangedData,
  DaemonApprovalModeChangedEvent,
  DaemonClientEvictedData,
  DaemonClientEvictedEvent,
  DaemonControlEvent,
  // Daemon-emitted resync
  // signal for SSE reconnects past the ring eviction boundary.
  DaemonStateResyncRequiredData,
  DaemonStateResyncRequiredEvent,
  DaemonMcpServerAddedData,
  DaemonMcpServerAddedEvent,
  DaemonMcpServerRemovedData,
  DaemonMcpServerRemovedEvent,
  DaemonMcpServerRestartedData,
  DaemonMcpServerRestartedEvent,
  DaemonMcpServerRestartRefusedData,
  DaemonMcpServerRestartRefusedEvent,
  DaemonSettingsReloadedData,
  DaemonSettingsReloadedEvent,
  DaemonSessionRewoundData,
  DaemonSessionRewoundEvent,
  DaemonSessionBranchedData,
  DaemonSessionBranchedEvent,
  DaemonToolToggledData,
  DaemonToolToggledEvent,
  DaemonWorkspaceInitializedData,
  DaemonWorkspaceInitializedEvent,
  DaemonEventEnvelope,
  DaemonKnownEventType,
  // MCP guardrail push-event types. See `mcp_guardrail_events`
  // capability tag and the `DaemonMcpGuardrailEvent` union below.
  DaemonMcpBudgetWarningData,
  DaemonMcpBudgetWarningEvent,
  DaemonMcpChildRefusedBatchData,
  DaemonMcpChildRefusedBatchEvent,
  DaemonMcpGuardrailEvent,
  DaemonMcpRefusedServer,
  DaemonMemoryChangedData,
  DaemonMemoryChangedEvent,
  DaemonModelSwitchedData,
  DaemonModelSwitchedEvent,
  DaemonModelSwitchFailedData,
  DaemonModelSwitchFailedEvent,
  DaemonPermissionOption,
  DaemonPermissionAlreadyResolvedData,
  DaemonPermissionAlreadyResolvedEvent,
  // Multi-client permission coordination push events.
  DaemonPermissionForbiddenData,
  DaemonPermissionForbiddenEvent,
  DaemonPermissionPartialVoteData,
  DaemonPermissionPartialVoteEvent,
  DaemonPermissionRequestData,
  DaemonPermissionRequestEvent,
  DaemonPermissionResolvedData,
  DaemonPermissionResolvedEvent,
  DaemonSessionClosedData,
  DaemonSessionClosedEvent,
  DaemonSessionClosedReason,
  DaemonSessionDiedData,
  DaemonSessionDiedEvent,
  DaemonSessionEvent,
  DaemonSessionMetadataUpdatedData,
  DaemonSessionMetadataUpdatedEvent,
  DaemonSessionUpdateData,
  DaemonSessionUpdateEvent,
  DaemonSessionViewState,
  DaemonSlowClientWarningData,
  DaemonSlowClientWarningEvent,
  DaemonStreamErrorData,
  DaemonStreamErrorEvent,
  DaemonStreamLifecycleEvent,
  DaemonWorkspaceMutationEvent,
  DaemonAuthDeviceFlowProviderId,
  DaemonAuthDeviceFlowStatus,
  DaemonAuthDeviceFlowErrorKind,
  DaemonAuthDeviceFlowStartedData,
  DaemonAuthDeviceFlowStartedEvent,
  DaemonAuthDeviceFlowThrottledData,
  DaemonAuthDeviceFlowThrottledEvent,
  DaemonAuthDeviceFlowAuthorizedData,
  DaemonAuthDeviceFlowAuthorizedEvent,
  DaemonAuthDeviceFlowFailedData,
  DaemonAuthDeviceFlowFailedEvent,
  DaemonAuthDeviceFlowCancelledData,
  DaemonAuthDeviceFlowCancelledEvent,
  DaemonAuthEvent,
  // Daemon assist push (server-side ghost-text suggestion)
  DaemonAssistEvent,
  DaemonFollowupSuggestionData,
  DaemonFollowupSuggestionEvent,
  // Non-blocking prompt completion events
  DaemonTurnEvent,
  DaemonTurnCompleteData,
  DaemonTurnCompleteEvent,
  DaemonTurnErrorData,
  DaemonTurnErrorEvent,
  // A5 — side-channel session snapshot
  DaemonSessionSnapshotData,
  DaemonSessionSnapshotEvent,
  DaemonDeviceFlowReducerState,
  DaemonAuthState,
  KnownDaemonEvent,
} from './events.js';
export type {
  DaemonAgentLevel,
  DaemonAgentMutationResult,
  DaemonGeneratedAgentContent,
  DaemonApprovalMode,
  DaemonApprovalModeResult,
  DaemonInitWorkspaceResult,
  DaemonMcpManageAction,
  DaemonMcpManageResult,
  DaemonMcpRestartResult,
  DaemonReloadResponse,
  DaemonRewindResult,
  DaemonRewindSnapshotInfo,
  DaemonSessionBtwResult,
  DaemonSessionRecapResult,
  DaemonShellCommandResult,
  DaemonRuntimeMcpAddRequest,
  DaemonRuntimeMcpAddResult,
  DaemonRuntimeMcpRemoveResult,
  DaemonToolToggleResult,
  DaemonSettingDescriptor,
  DaemonWorkspaceSettingsStatus,
  DaemonSettingUpdateResult,
  DaemonAvailableCommand,
  DaemonCapabilities,
  DaemonContextCategoryBreakdown,
  DaemonContextFileScope,
  DaemonContextMemoryDetail,
  DaemonContextSkillDetail,
  DaemonContextToolDetail,
  DaemonCreateAgentRequest,
  DaemonEnvCell,
  DaemonEnvKind,
  DaemonErrorKind,
  DaemonEvent,
  DaemonMcpDiscoveryState,
  DaemonMcpServerRuntimeStatus,
  DaemonMcpTransport,
  DaemonMode,
  DaemonProtocolVersions,
  BranchSessionRequest,
  DaemonBranchedSession,
  DaemonRestoredSession,
  DaemonSession,
  DaemonAuthProviderId,
  DaemonAuthProviderBaseUrlOption,
  DaemonAuthProviderCatalog,
  DaemonAuthProviderDescriptor,
  DaemonAuthProviderInstallRequest,
  DaemonAuthProviderInstallResult,
  DaemonAuthProviderModel,
  DaemonAuthDeviceFlowSdkStatus,
  DaemonAuthDeviceFlowSdkErrorKind,
  DaemonAuthProviderStatus,
  DaemonAuthStatusSnapshot,
  DaemonDeviceFlowStartResult,
  DaemonDeviceFlowState,
  DaemonSessionContextStatus,
  DaemonSessionAgentTaskStatus,
  DaemonSessionMonitorTaskStatus,
  DaemonSessionProcessTaskLifecycleStatus,
  DaemonSessionContextUsage,
  DaemonSessionContextUsageStatus,
  DaemonSessionState,
  DaemonSessionSummary,
  DaemonSessionShellTaskStatus,
  DaemonSessionSupportedCommandsStatus,
  DaemonSessionTaskLifecycleStatus,
  DaemonSessionTaskStatus,
  DaemonSessionTasksStatus,
  DaemonSessionStatsStatus,
  DaemonSessionStatsModelMetrics,
  DaemonSessionStatsToolByName,
  DaemonSkillLevel,
  DaemonPreflightCell,
  DaemonPreflightKind,
  DaemonStatus,
  DaemonStatusCell,
  DaemonUpdateAgentRequest,
  DaemonContentHash,
  DaemonWorkspaceAgentDetail,
  DaemonWorkspaceAgentSummary,
  DaemonWorkspaceAgentsStatus,
  DaemonWorkspaceEnvStatus,
  DaemonWorkspaceFile,
  DaemonWorkspaceFileBytes,
  DaemonWorkspaceFileEditRequest,
  DaemonWorkspaceFileEditResult,
  DaemonWorkspaceFileWriteRequest,
  DaemonWorkspaceFileWriteResult,
  DaemonWorkspaceMcpServerStatus,
  DaemonWorkspaceMcpStatus,
  DaemonWorkspaceMcpToolStatus,
  DaemonWorkspaceMcpToolsStatus,
  DaemonWorkspaceMemoryFile,
  DaemonWorkspaceMemoryStatus,
  DaemonWorkspacePreflightStatus,
  DaemonWorkspaceProviderCurrent,
  DaemonWorkspaceProviderModel,
  DaemonWorkspaceProviderStatus,
  DaemonWorkspaceProvidersStatus,
  DaemonWorkspaceSkillStatus,
  DaemonWorkspaceSkillsStatus,
  DaemonWorkspaceToolStatus,
  DaemonWorkspaceToolsStatus,
  DaemonWriteMemoryRequest,
  DaemonWriteMemoryResult,
  DaemonCommandHookConfig,
  DaemonFunctionHookConfig,
  DaemonHookConfig,
  DaemonHookEntry,
  DaemonHookEventMeta,
  DaemonHookEventName,
  DaemonHookMatcherKind,
  DaemonHookSource,
  DaemonHttpHookConfig,
  DaemonPromptHookConfig,
  DaemonSessionHooksStatus,
  DaemonUnknownHookConfig,
  DaemonWorkspaceHooksStatus,
  DaemonExtensionInstallType,
  DaemonExtensionOriginSource,
  DaemonExtensionCapabilities,
  DaemonExtensionEntry,
  DaemonWorkspaceExtensionsStatus,
  HeartbeatResult,
  MCPServerConfigShape,
  PermissionOutcome,
  PermissionOutcomeCancelled,
  PermissionOutcomeSelected,
  PermissionResponse,
  PromptContentBlock,
  PromptResult,
  PromptTextContent,
  SetModelResult,
  SetSessionLanguageResult,
  SessionMetadataResult,
} from './types.js';
