// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import lib from "./node-runtime.js";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;
import {} from '@ubjs/core';
const DEFINITIONS = {
    symbols: {
        rustbuffer_alloc: "ffi_cua_driver_contract_rustbuffer_alloc",
        rustbuffer_free: "ffi_cua_driver_contract_rustbuffer_free",
        rustbuffer_from_bytes: "ffi_cua_driver_contract_rustbuffer_from_bytes",
    },
    functions: {
        "ffi_cua_driver_contract_rust_future_poll_u8": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_u8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_u8": {
            args: [FfiType.Handle],
            ret: FfiType.UInt8,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_u8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_i8": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_i8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_i8": {
            args: [FfiType.Handle],
            ret: FfiType.Int8,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_i8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_u16": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_u16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_u16": {
            args: [FfiType.Handle],
            ret: FfiType.UInt16,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_u16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_i16": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_i16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_i16": {
            args: [FfiType.Handle],
            ret: FfiType.Int16,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_i16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_u32": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_u32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_u32": {
            args: [FfiType.Handle],
            ret: FfiType.UInt32,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_u32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_i32": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_i32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_i32": {
            args: [FfiType.Handle],
            ret: FfiType.Int32,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_i32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_u64": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_u64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_u64": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_u64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_i64": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_i64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_i64": {
            args: [FfiType.Handle],
            ret: FfiType.Int64,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_i64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_f32": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_f32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_f32": {
            args: [FfiType.Handle],
            ret: FfiType.Float32,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_f32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_f64": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_f64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_f64": {
            args: [FfiType.Handle],
            ret: FfiType.Float64,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_f64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_rust_buffer": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_rust_buffer": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_rust_buffer": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_rust_buffer": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_poll_void": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_cancel_void": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_rust_future_complete_void": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_contract_rust_future_free_void": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_contract_uniffi_contract_version": {
            args: [],
            ret: FfiType.UInt32,
            hasRustCallStatus: false,
        },
    },
    callbacks: {
        "RustFutureContinuationCallback": {
            args: [FfiType.Handle, FfiType.Int8],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ForeignFutureDroppedCallback": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
    },
    structs: {
        "ForeignFutureDroppedCallbackStruct": [
            { name: "handle", type: FfiType.Handle },
            { name: "free", type: FfiType.Callback("ForeignFutureDroppedCallback") },
        ],
    },
};
let _nativeModule;
const getter = () => {
    if (!_nativeModule) {
        const libPath = resolveLibPath({
            crateName: "cua_driver_sdk",
            callerUrl: import.meta.url,
            npmPackageBase: "@trycua/cua-driver-",
            tripleStyle: "node",
        });
        const mod_ = UniffiNativeModule.open(libPath);
        _nativeModule = mod_.register(DEFINITIONS);
    }
    return _nativeModule;
};
export default getter;
//# sourceMappingURL=cua_driver_contract-ffi.js.map