import { type UniffiRustCallStatus, type UniffiResult } from '@ubjs/core';
interface NativeModuleInterface {
    ffi_cua_driver_sdk_rust_future_poll_u8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_u8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_i8(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_u16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_u16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_i16(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_u32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_u32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_i32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_u64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_u64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cua_driver_sdk_rust_future_free_u64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_i64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_i64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cua_driver_sdk_rust_future_free_i64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_f32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_f32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_f32(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_f64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_f64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_sdk_rust_future_free_f64(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_rust_buffer(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_rust_buffer(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_cua_driver_sdk_rust_future_free_rust_buffer(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_poll_void(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_sdk_rust_future_cancel_void(handle: bigint): void;
    ffi_cua_driver_sdk_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    ffi_cua_driver_sdk_rust_future_free_void(handle: bigint): void;
    uniffi_cua_driver_sdk_fn_clone_cuadriver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_cuadriver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_cuadriversession(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_cuadriversession(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_driveractivityobserver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_driveractivityobserver(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_driverauthorizationhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_driverauthorizationhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_clone_embeddedcuadriverhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_free_embeddedcuadriverhost(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_init_callback_vtable_driveractivityobserver(vtable: UniffiVTableCallbackInterfaceCuaDriverSdkDriverActivityObserver): void;
    uniffi_cua_driver_sdk_fn_init_callback_vtable_driverauthorizationhost(vtable: UniffiVTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost): void;
    uniffi_cua_driver_sdk_fn_func_create_trusted_session(driver: bigint, options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_func_current_mac_os_permission_status(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_func_open_mac_os_screen_recording_settings(uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_func_request_mac_os_permissions(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect(socketPath: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect_with_client_kind(socketPath: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer(options: Uint8Array, observer: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind(options: Uint8Array, observer: bigint, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host(options: Uint8Array, host: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind(options: Uint8Array, host: bigint, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_client_kind(options: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations(options: Uint8Array, host: bigint, observer: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind(options: Uint8Array, host: bigint, observer: bigint, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker_with_client_kind(options: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_with_client_kind(options: Uint8Array, clientKind: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool(uniffiSelf: bigint, name: Uint8Array, argumentsJson: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_click(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_read(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_write(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_drag(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_end_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_execution_mode(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_agent_cursor_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_invoke_menu(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_is_available(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_metadata(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_press_key(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_runtime_scope_prefix(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_cuadriver_scroll(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_enabled(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_motion(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_theme(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_set_window_frame(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_shutdown(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_cuadriver_start_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_type_text(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriver_verify_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_call_tool(uniffiSelf: bigint, name: Uint8Array, argumentsJson: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_click(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_read(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_write(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_close(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_drag(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_end_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_escalate_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_agent_cursor_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_cursor_position(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_desktop_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_screen_size(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_get_session_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_hotkey(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_invoke_menu(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_move_cursor(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_press_key(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_scroll(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_enabled(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_motion(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_theme(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_set_window_frame(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_start_session(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_type_text(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_cuadriversession_verify_state(uniffiSelf: bigint, input: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_method_driveractivityobserver_on_activity(uniffiSelf: bigint, event: Uint8Array, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_cua_driver_sdk_fn_method_driverauthorizationhost_authorize(uniffiSelf: bigint, request: Uint8Array): bigint;
    uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_new(binaryPath: Uint8Array, hostBundleId: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_with_options(options: Uint8Array, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_connection(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_restart(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_start(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_state(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_stop(uniffiSelf: bigint): bigint;
    uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_wait_for_exit(uniffiSelf: bigint, generation: Uint8Array): bigint;
    ffi_cua_driver_sdk_uniffi_contract_version(): number;
    uniffi_cua_driver_sdk_checksum_func_create_trusted_session(): number;
    uniffi_cua_driver_sdk_checksum_func_current_mac_os_permission_status(): number;
    uniffi_cua_driver_sdk_checksum_func_open_mac_os_screen_recording_settings(): number;
    uniffi_cua_driver_sdk_checksum_func_request_mac_os_permissions(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_with_client_kind(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_click(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_read(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_write(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_drag(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_execution_mode(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_agent_cursor_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_invoke_menu(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_metadata(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_runtime_scope_prefix(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_enabled(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_motion(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_theme(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_set_window_frame(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_shutdown(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriver_verify_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_call_tool(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_click(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_read(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_write(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_close(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_drag(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_end_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_escalate_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_agent_cursor_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_cursor_position(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_desktop_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_screen_size(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_session_state(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_hotkey(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_invoke_menu(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_move_cursor(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_press_key(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_scroll(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_enabled(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_motion(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_theme(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_window_frame(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_start_session(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_type_text(): number;
    uniffi_cua_driver_sdk_checksum_method_cuadriversession_verify_state(): number;
    uniffi_cua_driver_sdk_checksum_method_driveractivityobserver_on_activity(): number;
    uniffi_cua_driver_sdk_checksum_method_driverauthorizationhost_authorize(): number;
    uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_new(): number;
    uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_with_options(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_connection(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_restart(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_start(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_state(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_stop(): number;
    uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_wait_for_exit(): number;
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}
declare const getter: () => NativeModuleInterface;
export default getter;
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
    handle: bigint;
    free: UniffiForeignFutureDroppedCallback;
};
type UniffiCallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0 = (uniffiHandle: bigint, event: Uint8Array) => UniffiResult<void>;
type UniffiCallbackInterfaceCloneCuaDriverSdkDriverActivityObserver = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeCuaDriverSdkDriverActivityObserver = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceCuaDriverSdkDriverActivityObserver = {
    uniffi_free: UniffiCallbackInterfaceFreeCuaDriverSdkDriverActivityObserver;
    uniffi_clone: UniffiCallbackInterfaceCloneCuaDriverSdkDriverActivityObserver;
    on_activity: UniffiCallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0;
};
export type UniffiForeignFutureResultRustBuffer = {
    return_value: Uint8Array;
    call_status: UniffiRustCallStatus;
};
export type UniffiForeignFutureCompleterustBuffer = (callbackData: bigint, result: UniffiForeignFutureResultRustBuffer) => void;
type UniffiCallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0 = (uniffiHandle: bigint, request: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceCloneCuaDriverSdkDriverAuthorizationHost = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeCuaDriverSdkDriverAuthorizationHost = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost = {
    uniffi_free: UniffiCallbackInterfaceFreeCuaDriverSdkDriverAuthorizationHost;
    uniffi_clone: UniffiCallbackInterfaceCloneCuaDriverSdkDriverAuthorizationHost;
    authorize: UniffiCallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0;
};
