// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
import lib from "./node-runtime.js";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;
import {} from '@ubjs/core';
const DEFINITIONS = {
    symbols: {
        rustbuffer_alloc: "ffi_cua_driver_sdk_rustbuffer_alloc",
        rustbuffer_free: "ffi_cua_driver_sdk_rustbuffer_free",
        rustbuffer_from_bytes: "ffi_cua_driver_sdk_rustbuffer_from_bytes",
    },
    functions: {
        "ffi_cua_driver_sdk_rust_future_poll_u8": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_u8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_u8": {
            args: [FfiType.Handle],
            ret: FfiType.UInt8,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_u8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_i8": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_i8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_i8": {
            args: [FfiType.Handle],
            ret: FfiType.Int8,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_i8": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_u16": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_u16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_u16": {
            args: [FfiType.Handle],
            ret: FfiType.UInt16,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_u16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_i16": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_i16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_i16": {
            args: [FfiType.Handle],
            ret: FfiType.Int16,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_i16": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_u32": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_u32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_u32": {
            args: [FfiType.Handle],
            ret: FfiType.UInt32,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_u32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_i32": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_i32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_i32": {
            args: [FfiType.Handle],
            ret: FfiType.Int32,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_i32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_u64": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_u64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_u64": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_u64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_i64": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_i64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_i64": {
            args: [FfiType.Handle],
            ret: FfiType.Int64,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_i64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_f32": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_f32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_f32": {
            args: [FfiType.Handle],
            ret: FfiType.Float32,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_f32": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_f64": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_f64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_f64": {
            args: [FfiType.Handle],
            ret: FfiType.Float64,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_f64": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_rust_buffer": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_rust_buffer": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_rust_buffer": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_rust_buffer": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_poll_void": {
            args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_cancel_void": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_rust_future_complete_void": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "ffi_cua_driver_sdk_rust_future_free_void": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_clone_cuadriver": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_free_cuadriver": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_clone_cuadriversession": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_free_cuadriversession": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_clone_driveractivityobserver": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_free_driveractivityobserver": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_clone_driverauthorizationhost": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_free_driverauthorizationhost": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_clone_embeddedcuadriverhost": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_free_embeddedcuadriverhost": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_init_callback_vtable_driveractivityobserver": {
            args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceCuaDriverSdkDriverActivityObserver"))],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_init_callback_vtable_driverauthorizationhost": {
            args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost"))],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_func_create_trusted_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_func_current_mac_os_permission_status": {
            args: [],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_func_open_mac_os_screen_recording_settings": {
            args: [],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_func_request_mac_os_permissions": {
            args: [],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect": {
            args: [FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_connect_with_client_kind": {
            args: [FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create": {
            args: [FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured": {
            args: [FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer": {
            args: [FfiType.RustBuffer, FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind": {
            args: [FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host": {
            args: [FfiType.RustBuffer, FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind": {
            args: [FfiType.RustBuffer, FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_client_kind": {
            args: [FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations": {
            args: [FfiType.RustBuffer, FfiType.Handle, FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind": {
            args: [FfiType.RustBuffer, FfiType.Handle, FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker": {
            args: [FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_private_worker_with_client_kind": {
            args: [FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_cuadriver_create_with_client_kind": {
            args: [FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_call_tool": {
            args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_click": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_read": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_clipboard_write": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_drag": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_end_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_escalate_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_execution_mode": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_get_agent_cursor_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_get_cursor_position": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_get_desktop_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_get_screen_size": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_get_session_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_hotkey": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_invoke_menu": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_is_available": {
            args: [FfiType.Handle],
            ret: FfiType.Int8,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_list_tools_json": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_metadata": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_move_cursor": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_press_key": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_runtime_scope_prefix": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_scroll": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_enabled": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_motion": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_set_agent_cursor_theme": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_set_window_frame": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_shutdown": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_socket_path": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_start_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_type_text": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriver_verify_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_call_tool": {
            args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_click": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_read": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_clipboard_write": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_close": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_drag": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_end_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_escalate_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_agent_cursor_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_cursor_position": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_desktop_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_screen_size": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_get_session_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_hotkey": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_invoke_menu": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_move_cursor": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_press_key": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_scroll": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_enabled": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_motion": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_agent_cursor_theme": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_set_window_frame": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_start_session": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_type_text": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_cuadriversession_verify_state": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_driveractivityobserver_on_activity": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Void,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_driverauthorizationhost_authorize": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_new": {
            args: [FfiType.RustBuffer, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_constructor_embeddedcuadriverhost_with_options": {
            args: [FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_connection": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_restart": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_start": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_state": {
            args: [FfiType.Handle],
            ret: FfiType.RustBuffer,
            hasRustCallStatus: true,
        },
        "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_stop": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_fn_method_embeddedcuadriverhost_wait_for_exit": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "ffi_cua_driver_sdk_uniffi_contract_version": {
            args: [],
            ret: FfiType.UInt32,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_func_create_trusted_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_func_current_mac_os_permission_status": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_func_open_mac_os_screen_recording_settings": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_func_request_mac_os_permissions": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_connect_with_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_activity_observer_and_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_authorization_host_and_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_configured_with_host_integrations_and_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_private_worker_with_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_cuadriver_create_with_client_kind": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_call_tool": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_click": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_read": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_clipboard_write": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_drag": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_end_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_escalate_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_execution_mode": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_agent_cursor_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_cursor_position": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_desktop_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_screen_size": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_get_session_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_hotkey": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_invoke_menu": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_is_available": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_list_tools_json": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_metadata": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_move_cursor": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_press_key": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_runtime_scope_prefix": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_scroll": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_enabled": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_motion": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_agent_cursor_theme": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_set_window_frame": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_shutdown": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_socket_path": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_start_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_type_text": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriver_verify_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_call_tool": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_click": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_read": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_clipboard_write": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_close": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_drag": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_end_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_escalate_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_agent_cursor_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_cursor_position": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_desktop_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_screen_size": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_get_session_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_hotkey": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_invoke_menu": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_move_cursor": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_press_key": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_scroll": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_enabled": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_motion": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_agent_cursor_theme": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_set_window_frame": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_start_session": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_type_text": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_cuadriversession_verify_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_driveractivityobserver_on_activity": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_driverauthorizationhost_authorize": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_new": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_constructor_embeddedcuadriverhost_with_options": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_connection": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_restart": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_start": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_state": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_stop": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
        "uniffi_cua_driver_sdk_checksum_method_embeddedcuadriverhost_wait_for_exit": {
            args: [],
            ret: FfiType.UInt16,
            hasRustCallStatus: false,
        },
    },
    callbacks: {
        "RustFutureContinuationCallback": {
            args: [FfiType.Handle, FfiType.Int8],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ForeignFutureDroppedCallback": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "CallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0": {
            args: [FfiType.Handle, FfiType.RustBuffer],
            ret: FfiType.VoidPointer,
            hasRustCallStatus: true,
            outReturn: true,
        },
        "CallbackInterfaceCloneCuaDriverSdk_DriverActivityObserver": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "CallbackInterfaceFreeCuaDriverSdk_DriverActivityObserver": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "ForeignFutureCompleterust_buffer": {
            args: [FfiType.Handle, FfiType.Struct("ForeignFutureResultRustBuffer")],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
        "CallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0": {
            args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
            ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
            hasRustCallStatus: false,
            outReturn: true,
        },
        "CallbackInterfaceCloneCuaDriverSdk_DriverAuthorizationHost": {
            args: [FfiType.Handle],
            ret: FfiType.Handle,
            hasRustCallStatus: false,
        },
        "CallbackInterfaceFreeCuaDriverSdk_DriverAuthorizationHost": {
            args: [FfiType.Handle],
            ret: FfiType.Void,
            hasRustCallStatus: false,
        },
    },
    structs: {
        "ForeignFutureDroppedCallbackStruct": [
            { name: "handle", type: FfiType.Handle },
            { name: "free", type: FfiType.Callback("ForeignFutureDroppedCallback") },
        ],
        "VTableCallbackInterfaceCuaDriverSdkDriverActivityObserver": [
            { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeCuaDriverSdk_DriverActivityObserver") },
            { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneCuaDriverSdk_DriverActivityObserver") },
            { name: "on_activity", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkDriverActivityObserverMethod0") },
        ],
        "ForeignFutureResultRustBuffer": [
            { name: "return_value", type: FfiType.RustBuffer },
            { name: "call_status", type: FfiType.RustCallStatus },
        ],
        "VTableCallbackInterfaceCuaDriverSdkDriverAuthorizationHost": [
            { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeCuaDriverSdk_DriverAuthorizationHost") },
            { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneCuaDriverSdk_DriverAuthorizationHost") },
            { name: "authorize", type: FfiType.Callback("CallbackInterfaceCuaDriverSdkDriverAuthorizationHostMethod0") },
        ],
    },
};
let _nativeModule;
const getter = () => {
    if (!_nativeModule) {
        const libPath = resolveLibPath({
            crateName: "cua_driver_sdk",
            callerUrl: import.meta.url,
            npmPackageBase: "@trycua/cua-driver-",
            tripleStyle: "node",
        });
        const mod_ = UniffiNativeModule.open(libPath);
        _nativeModule = mod_.register(DEFINITIONS);
    }
    return _nativeModule;
};
export default getter;
//# sourceMappingURL=cua_driver_sdk-ffi.js.map