import { type UniffiRustCallStatus } from '@ubjs/core';
interface NativeModuleInterface {
    ffi_cua_driver_contract_rust_future_poll_u8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_u8(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_u8(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_i8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_i8(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_i8(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_u16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_u16(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_u16(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_i16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_i16(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_i16(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_u32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_u32(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_u32(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_i32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_i32(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_i32(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_u64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_u64(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cua_driver_contract_rust_future_free_u64(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_i64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_i64(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_cua_driver_contract_rust_future_free_i64(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_f32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_f32(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_f32(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_f64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_f64(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_cua_driver_contract_rust_future_free_f64(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_rust_buffer(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_rust_buffer(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_cua_driver_contract_rust_future_free_rust_buffer(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_poll_void(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_cua_driver_contract_rust_future_cancel_void(handle: bigint): void;
    ffi_cua_driver_contract_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    ffi_cua_driver_contract_rust_future_free_void(handle: bigint): void;
    ffi_cua_driver_contract_uniffi_contract_version(): number;
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}
declare const getter: () => NativeModuleInterface;
export default getter;
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
    handle: bigint;
    free: UniffiForeignFutureDroppedCallback;
};
