// Generated by uniffi-bindgen-react-native — do not edit.
export * from './cua_driver_contract.js';
export * from './cua_driver_sdk.js';
import * as cua_driver_contract from './cua_driver_contract.js';
import * as cua_driver_sdk from './cua_driver_sdk.js';
let initialized = false;
if (!initialized) {
    cua_driver_contract.default.initialize();
    cua_driver_sdk.default.initialize();
    initialized = true;
}
export async function uniffiInitAsync() { }
export default {
    cua_driver_contract,
    cua_driver_sdk,
};
//# sourceMappingURL=index.js.map