import type { AudioInputDevice } from '../shared/host-api.ts';
type AudioDiagnosticDetails = Readonly<Record<string, string | number | boolean | undefined>>;
export declare class HostAudioEngine {
    private readonly onInputLevel;
    private readonly onDiagnostic;
    private captureContext;
    private captureStream;
    private captureOutputStream;
    private captureSource;
    private captureNode;
    private outputContext;
    private outputSources;
    private outputCursor;
    private outputGeneration;
    private outputMuted;
    private captureRequested;
    private inputMuted;
    private captureEpoch;
    private captureGeneration;
    private mediaDeviceListenerInstalled;
    private microphoneAllowed;
    private serviceActive;
    private selfCheckGeneration;
    private firstCaptureFrameEpoch;
    private readonly lifecycle;
    constructor(onInputLevel?: (level: number) => void, onDiagnostic?: (event: string, details: AudioDiagnosticDetails) => void);
    private readonly handleDeviceChange;
    initialize(microphoneAllowed: boolean): Promise<void>;
    listInputDevices(): Promise<AudioInputDevice[]>;
    setInputDevice(deviceId?: string): Promise<void>;
    recheck(reason: string): Promise<void>;
    private recheckCurrent;
    private runSelfCheck;
    setCapture(enabled: boolean, muted: boolean, epoch?: number): Promise<void>;
    private setCaptureCurrent;
    setOutputMuted(muted: boolean): void;
    play(frame: Uint8Array): Promise<void>;
    clearOutput(): void;
    dispose(): Promise<void>;
    private checkInput;
    private checkOutput;
    private ensureOutputContext;
    private startCapture;
    private stopCapture;
    private refreshCaptureInput;
    private monitorInputTracks;
    private setCaptureMuted;
    private reportCaptureError;
    private selectedInputDeviceId;
    private openInputStream;
    private resetAudioContexts;
    private installMediaDeviceListener;
}
export {};
