/**
 * Qwen Code Backend (ACP SDK Client)
 *
 * Spawns Qwen Code in ACP mode and adapts ACP session updates into Craft's
 * provider-agnostic AgentEvent stream.
 */
import type { AgentEvent } from '@craft-agent/core/types';
import type { FileAttachment } from '../utils/files.ts';
import type { ModelFetchResult } from '../config/model-fetcher.ts';
import { BaseAgent } from './base-agent.ts';
import type { BackendConfig, BackendSessionMessagesResult, AvailableCommandsSnapshot, BackendSessionListOptions, BackendSessionListResult, BackendRewindResult, ChatOptions, BackendHostRuntimeContext, MidTurnMessageMetadata, SdkMcpServerConfig } from './backend/types.ts';
import { AbortReason } from './backend/types.ts';
import type { PermissionMode } from './mode-manager.ts';
import { type LLMQueryRequest, type LLMQueryResult } from './llm-tool.ts';
import type { PermissionResponseOptions, PermissionRuleType, PermissionSettingsScope, QwenCoreSettingKey, QwenCoreSettingsSnapshot, QwenHookDefinition, QwenHookEvent, QwenMcpServerConfig, QwenPermissionSettings, QwenProviderCatalog, QwenProviderConnectParams, QwenProviderConnectResult, QwenSettingValue, QwenSettingsScope, QwenSkillDeleteRequest, QwenSkillDeleteResult, QwenSkillInstallRequest, QwenSkillInstallResult, QwenSkillSetEnabledRequest, QwenSkillSetEnabledResult } from '../protocol/dto.ts';
import type { QwenMemoryPaths, QwenMemorySettings } from '../config/qwen-settings.ts';
export declare function formatQwenAcpErrorMessage(error: unknown): string;
type QwenSettingsAcpOptions = {
    hostRuntime: BackendHostRuntimeContext;
    cwd?: string;
    processCwd?: string;
    envOverrides?: Record<string, string>;
    timeoutMs?: number;
    debug?: (message: string) => void;
};
export declare function getQwenMemorySettingsViaAcp(options: QwenSettingsAcpOptions): Promise<QwenMemorySettings>;
export declare function setQwenMemorySettingsViaAcp(options: QwenSettingsAcpOptions, updates: Partial<QwenMemorySettings>): Promise<QwenMemorySettings>;
export declare function getQwenSettingsPathViaAcp(options: QwenSettingsAcpOptions): Promise<string>;
export declare function getQwenCoreSettingsViaAcp(options: QwenSettingsAcpOptions): Promise<QwenCoreSettingsSnapshot>;
export declare function setQwenCoreSettingViaAcp(options: QwenSettingsAcpOptions, scope: QwenSettingsScope, key: QwenCoreSettingKey, value: QwenSettingValue): Promise<QwenCoreSettingsSnapshot>;
export declare function setQwenMcpServerViaAcp(options: QwenSettingsAcpOptions, scope: QwenSettingsScope, name: string, server: QwenMcpServerConfig): Promise<QwenCoreSettingsSnapshot>;
export declare function removeQwenMcpServerViaAcp(options: QwenSettingsAcpOptions, scope: QwenSettingsScope, name: string): Promise<QwenCoreSettingsSnapshot>;
export declare function setQwenHookViaAcp(options: QwenSettingsAcpOptions, scope: QwenSettingsScope, event: QwenHookEvent, index: number | undefined, hook: QwenHookDefinition): Promise<QwenCoreSettingsSnapshot>;
export declare function removeQwenHookViaAcp(options: QwenSettingsAcpOptions, scope: QwenSettingsScope, event: QwenHookEvent, index: number): Promise<QwenCoreSettingsSnapshot>;
export declare function setQwenExtensionSettingViaAcp(options: QwenSettingsAcpOptions, extensionId: string, settingKey: string, scope: QwenSettingsScope, value: QwenSettingValue): Promise<QwenCoreSettingsSnapshot>;
export declare function getQwenPermissionSettingsViaAcp(options: QwenSettingsAcpOptions): Promise<QwenPermissionSettings>;
export declare function setQwenPermissionRulesViaAcp(options: QwenSettingsAcpOptions, scope: PermissionSettingsScope, ruleType: PermissionRuleType, rules: string[]): Promise<QwenPermissionSettings>;
export declare function getQwenMemoryPathsViaAcp(options: QwenSettingsAcpOptions & {
    projectRoot?: string;
}): Promise<QwenMemoryPaths>;
export declare function listQwenProvidersViaAcp(options: QwenSettingsAcpOptions): Promise<QwenProviderCatalog>;
export declare function getQwenWorkspacePreflightViaAcp(options: QwenSettingsAcpOptions): Promise<Record<string, unknown>>;
export declare function fetchQwenModelsViaSharedAcp(options: QwenSettingsAcpOptions): Promise<ModelFetchResult>;
export declare function connectQwenProviderViaAcp(options: QwenSettingsAcpOptions, params: QwenProviderConnectParams): Promise<QwenProviderConnectResult>;
export declare function extractQwenParentToolUseId(update: Record<string, unknown>): string | undefined;
export declare function resolveQwenParentToolUseId(args: {
    update: Record<string, unknown>;
    toolUseId?: string;
    activeParentToolUseIds?: ReadonlySet<string>;
}): string | undefined;
export declare class QwenAgent extends BaseAgent {
    protected backendName: string;
    private acpLease;
    private connection;
    private qwenSessionId;
    private ensureQwenSessionPromise;
    private eventQueue;
    private _isProcessing;
    private abortReason?;
    private persistedQwenSessionId;
    private qwenPersistenceCwd;
    private activePromptRunId;
    private promptRunCounter;
    private permissionRequestCounter;
    private toolIdCounter;
    private planUpdateCounter;
    private hasInitialModeOverride;
    private pendingModeOverride;
    private pendingPermissions;
    private miniCollectors;
    private historyCollectors;
    private ensureProcessPromise;
    private suppressedSessionUpdates;
    private pendingAvailableCommandsUpdates;
    private latestAvailableCommandsSnapshot;
    private availableCommandsWaiters;
    private availableModelIds;
    private availableModelsById;
    private firstAvailableModelId;
    private sourceMcpServers;
    private currentTurnId;
    private currentAssistantText;
    private currentThoughtText;
    private currentAssistantParentToolUseId;
    private currentThoughtParentToolUseId;
    private currentIsSlashCommand;
    private capturedUsageInCurrentTurn;
    private usageWaiters;
    private toolNames;
    private toolInputs;
    private activeParentToolUseIds;
    private midTurnMessageQueue;
    constructor(config: BackendConfig);
    getRecentStderr(): string;
    getSessionId(): string | null;
    setSessionId(sessionId: string | null): void;
    clearHistory(): void;
    protected extractSkillPaths(message: string): {
        skillPaths: Map<string, string>;
        cleanMessage: string;
        missingSkills: string[];
    };
    updateWorkingDirectory(path: string): void;
    private invalidateAvailableCommandsSnapshot;
    protected chatImpl(messageParam: string, attachments?: FileAttachment[], options?: ChatOptions): AsyncGenerator<AgentEvent>;
    isProcessing(): boolean;
    private waitForCurrentTurnUsage;
    private resolveUsageWaiters;
    enqueueMidTurnMessage(message: string, attachments?: FileAttachment[], metadata?: MidTurnMessageMetadata): boolean;
    abort(reason?: string): Promise<void>;
    forceAbort(reason: AbortReason): void;
    respondToPermission(requestId: string, allowed: boolean, alwaysAllow?: boolean, options?: PermissionResponseOptions): void;
    setPermissionMode(mode: PermissionMode): void;
    cyclePermissionMode(): PermissionMode;
    getPermissionSettings(): Promise<QwenPermissionSettings>;
    setPermissionRules(scope: PermissionSettingsScope, ruleType: PermissionRuleType, rules: string[]): Promise<QwenPermissionSettings>;
    getCoreSettings(): Promise<QwenCoreSettingsSnapshot>;
    listProviders(): Promise<QwenProviderCatalog>;
    connectProvider(params: QwenProviderConnectParams): Promise<QwenProviderConnectResult>;
    setCoreSetting(scope: QwenSettingsScope, key: QwenCoreSettingKey, value: QwenSettingValue): Promise<QwenCoreSettingsSnapshot>;
    setMcpServer(scope: QwenSettingsScope, name: string, server: QwenMcpServerConfig): Promise<QwenCoreSettingsSnapshot>;
    removeMcpServer(scope: QwenSettingsScope, name: string): Promise<QwenCoreSettingsSnapshot>;
    setHook(scope: QwenSettingsScope, event: QwenHookEvent, index: number | undefined, hook: QwenHookDefinition): Promise<QwenCoreSettingsSnapshot>;
    removeHook(scope: QwenSettingsScope, event: QwenHookEvent, index: number): Promise<QwenCoreSettingsSnapshot>;
    setExtensionSetting(extensionId: string, settingKey: string, scope: QwenSettingsScope, value: QwenSettingValue): Promise<QwenCoreSettingsSnapshot>;
    installSkill(request: QwenSkillInstallRequest): Promise<QwenSkillInstallResult>;
    deleteSkill(request: QwenSkillDeleteRequest): Promise<QwenSkillDeleteResult>;
    setSkillEnabled(request: QwenSkillSetEnabledRequest): Promise<QwenSkillSetEnabledResult>;
    setModel(model: string): void;
    setSourceServers(mcpServers: Record<string, SdkMcpServerConfig>, apiServers: Record<string, unknown>, intendedSlugs?: string[]): Promise<void>;
    runMiniCompletion(prompt: string): Promise<string | null>;
    listSessions(options?: BackendSessionListOptions): Promise<BackendSessionListResult>;
    deleteBackendSession(sessionId: string, options?: {
        cwd?: string;
    }): Promise<boolean>;
    rewindToUserTurn(targetTurnIndex: number): Promise<BackendRewindResult>;
    renameBackendSession(sessionId: string, title: string, options?: {
        cwd?: string;
    }): Promise<boolean>;
    loadSessionMessages(sessionId: string, options?: {
        cwd?: string;
    }): Promise<BackendSessionMessagesResult>;
    refreshAvailableCommands(): Promise<AvailableCommandsSnapshot | null>;
    queryLlm(request: LLMQueryRequest): Promise<LLMQueryResult>;
    destroy(): void;
    private ensureProcess;
    private startProcess;
    private buildSpawnCommand;
    private handleExtMethod;
    private getAcpConnection;
    private callAcp;
    private withTimeout;
    private handleProcessExit;
    private killSubprocess;
    private registerAcpSession;
    private unregisterAcpSession;
    private ensureQwenSession;
    private createOrLoadQwenSession;
    private reloadCurrentSessionForAvailableCommands;
    private createEphemeralSession;
    private recordSessionModels;
    private isKnownAvailableModel;
    private getCurrentModelContextWindow;
    private applyCurrentModelContextWindow;
    private recordSessionModes;
    private forwardModel;
    private applySessionSettings;
    private forwardPermissionMode;
    private resolvedCwd;
    private resolveQwenPersistenceCwd;
    private extractQwenRecordText;
    private getQwenTranscriptPatchContent;
    private isPatchableQwenUserRecord;
    private persistQwenTranscriptTextElements;
    private readQwenTranscriptTextElements;
    private applyQwenTranscriptTextElements;
    private buildAcpMcpServers;
    private buildPromptBlocks;
    private buildCraftContext;
    private buildQueryPrompt;
    private handleSessionUpdate;
    private collectMiniUpdate;
    private buildHistoryMessages;
    private mergeQwenTranscriptTelemetryMessages;
    private loadQwenTranscriptTelemetryMessages;
    private extractQwenTranscriptToolResult;
    private buildQwenTranscriptTelemetryMessage;
    private resolveQwenTranscriptTelemetryParent;
    private mergeSlashCommandInvocationMessages;
    private isSameSlashCommandInvocationMessage;
    private loadSlashCommandInvocationMessages;
    private handleAgentMessageChunk;
    private handleAgentThoughtChunk;
    private flushPendingTextAsIntermediate;
    private flushThoughtText;
    private flushAssistantText;
    private handleToolCall;
    private handleToolCallUpdate;
    private handlePlanUpdate;
    private handleModeUpdate;
    private applyAcpPermissionMode;
    private parseAvailableCommandsUpdate;
    private extractAvailableCommandsSnapshot;
    private extractLatestTokenUsage;
    private handleAvailableCommandsUpdate;
    private handleOrStoreAvailableCommandsUpdate;
    private flushPendingAvailableCommandsUpdate;
    private waitForAvailableCommandsSnapshot;
    private resolveAvailableCommandsWaiters;
    private formatToolResult;
    private captureUsage;
    private captureUsageInto;
    private extractUsage;
    private handlePermissionRequest;
    private permissionImpact;
    private selectPermissionOption;
    private createPermissionResponse;
    private cancelPendingPermissions;
    private resolvePendingPermission;
    protected debug(message: string): void;
}
export { QwenAgent as QwenBackend };
