export const CHANNEL_DAEMON_WORKER_SENTINEL = 'QWEN_CHANNEL_DAEMON_WORKER';
export const CHANNEL_WORKER_HEARTBEAT_INTERVAL_MS = 15_000;
export const QWEN_DAEMON_TOKEN_ENV = 'QWEN_DAEMON_TOKEN';
export const QWEN_DAEMON_URL_ENV = 'QWEN_DAEMON_URL';
export const QWEN_DAEMON_WORKSPACE_ENV = 'QWEN_DAEMON_WORKSPACE';
export const QWEN_SERVER_TOKEN_ENV = 'QWEN_SERVER_TOKEN';
