export declare const CHANNEL_DAEMON_WORKER_SENTINEL = "QWEN_CHANNEL_DAEMON_WORKER";
export declare const CHANNEL_WORKER_HEARTBEAT_INTERVAL_MS = 15000;
export declare const QWEN_DAEMON_TOKEN_ENV = "QWEN_DAEMON_TOKEN";
export declare const QWEN_DAEMON_URL_ENV = "QWEN_DAEMON_URL";
export declare const QWEN_DAEMON_WORKSPACE_ENV = "QWEN_DAEMON_WORKSPACE";
export declare const QWEN_SERVER_TOKEN_ENV = "QWEN_SERVER_TOKEN";
